const veteransDataU = [
  {
    "Surname": "Ujdur",
    "Christian Name": "Ben",
    "Unit": "Ry Con Coy Reinfs",
    "Regtl. Number": "44596",
    "Rank": "Spr",
    "Embarkation Dates": "A 41- J 41",
    "Marital Status": "S",
    "Enlistment": "Kaitaia",
    "Occupation": "Labourer PWD",
    "Address": "Waipapakauri",
    "Next of Kin": "Mr M Ujdur, Waipapakauri f",
    "Where Killed or Died": "Italy",
    "Cemetery Name": "Bari War Italy",
    "Grave/Memorial Reference": "VII C 2",
    "Last rank Held": "Sgt",
    "Date of Birth": "1916",
    "Date of Death": "Sat Jan 13 1945 190000 GMT1200 New Zealand Daylight Time",
    "Age": "28",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Waipapakauri Cemetery Wapapakauri Alphabet Blocks Block X Plot 3",
    "Funeral Director": "Unknown",
    "Place of birth": "Ahipara",
    "AL": "Y",
    "Notes": "MID. Two other brothers served: Nicholas Ujdur and Sydney Ujdur. Son of Mate and Emily Mangai Ujdur, nee Arano, (Allen), (Arona), of Waipapakauri. Place of birth; Ahipara. He appears to have been reinterred at the Waipapakauri Cemetery, Waipapakauri. Age on burial record differs. Ancestrylibrary.com.au. http://www.reynoldmacpherson.ac.nz/publications/The 20McPhersons 20from 20Inverkeithny 20in 20New 20Zealand, 201770-2014 2026 20August 202014.pdf"
  },
  {
    "Surname": "Ujdur",
    "Christian Name": "Nicholas",
    "Unit": "14 Lt A A Regt",
    "Name Variation": "Ujdur, Nick",
    "Regtl. Number": "61189",
    "Rank": "Gnr",
    "Embarkation Dates": "A 41- J 41",
    "Marital Status": "S",
    "Enlistment": "Kaitaia",
    "Occupation": "Forestry Labourer",
    "Address": "Waipapakauri",
    "Next of Kin": "Mr M Ujdur, Waipapakauri f",
    "Last rank Held": "Sgt",
    "Date of Birth": "Thu May 14 1914 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sun Dec 27 1987 210000 GMT1300 New Zealand Daylight Time",
    "Age": "73",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Waipapakauri Cemetery Waipapakauri Alphabet Blocks Block X Plot 17",
    "Funeral Director": "Unknown",
    "Husbands/Wives/Partners": "Jeanette Miller",
    "Place of birth": "Ahipara or Houhora",
    "Place of death": "Waipapakauri",
    "AL": "Y",
    "Notes": "Two other brothers served: Ben Ujdur (who fell) and Sydney Ujdur. Son of Mate and Emily Mangai Ujdur, nee Arano, (Allen), (Arona), of Waipapakauri. Husband of Jeanette Ujdur, nee Miller. Place of birth: Ahipara or Houhora. Place of death: Waipapakauri. Familysearch.org. Ancestrylibrary.com.au http://www.reynoldmacpherson.ac.nz/publications/The 20McPhersons 20from 20Inverkeithny 20in 20New 20Zealand, 201770-2014 2026 20August 202014.pdf"
  },
  {
    "Surname": "Ujdur",
    "Christian Name": "Sydney",
    "Unit": "14 Lt A A Regt",
    "Name Variation": "Ujdur, Sid",
    "Regtl. Number": "61190",
    "Rank": "Gnr",
    "Embarkation Dates": "A 41- J 41",
    "Marital Status": "S",
    "Enlistment": "Kaitaia",
    "Occupation": "Forestry Labourer",
    "Address": "Waipapakauri",
    "Next of Kin": "Mr M Ujdur, P O, Waipapakauri f",
    "Last rank Held": "Sgt",
    "Date of Birth": "Sat Jul 24 1915 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Thu Dec 18 2008 210000 GMT1300 New Zealand Daylight Time",
    "Age": "93",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Houhora Cemetery Houhora New Public Lawn Block A Plot 1",
    "Funeral Director": "Unknown",
    "Husbands/Wives/Partners": "Lillian Ujdur",
    "Place of birth": "Ahipara or Waipapakauri",
    "Place of death": "At home New Zealand",
    "AL": "Y",
    "Notes": "Two other brothers served: Ben Ujdur (who fell) and Nicholas Ujdur. Son of Mate and Emily Mangai Ujdur, nee Arano, (Allen), (Arona), of Waipapakauri. Husband of Lillian Ujdur. Place of birth: Ahipara or Waipapakauri. Place of death: At home, New Zealand. Familysearch.org. Ancestrylibrary.com.au. http://www.reynoldmacpherson.ac.nz/publications/The 20McPhersons 20from 20Inverkeithny 20in 20New 20Zealand, 201770-2014 2026 20August 202014.pdf"
  },
  {
    "Surname": "Underhill",
    "Christian Name": "Douglas William",
    "Unit": "Inf Reinfs",
    "Regtl. Number": "623809",
    "Rank": "Pte",
    "Embarkation Dates": "J 45-D 45",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Act fireman",
    "Address": "N.Z.R., Maungaturoto Railway",
    "Next of Kin": "Mrs L B Underhill, Thornton's Bay m",
    "Date of Birth": "Tue Feb 19 1924 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat Sep 10 2022 190000 GMT1200 New Zealand Standard Time",
    "Age": "98",
    "Husbands/Wives/Partners": "Heather Oliver Underhill",
    "Place of birth": "NZ",
    "AL": "Y",
    "Notes": "Son of Joseph and Laura Bessie Underhill, nee Cooper, of Thorntons Bay. Husband of Heather Oliver Underhill. 1963 Raglan Electoral Roll. Place of birth: New Zealand. Ancestry.com. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Underwood",
    "Christian Name": "Claude Edgar",
    "Unit": "29 Bn",
    "Regtl. Number": "26561",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Rotorua",
    "Occupation": "Mill hand",
    "Address": "No 3 Mill, Mokai",
    "Next of Kin": "Mr Edward Underwood, Rawene f",
    "Date of Birth": "Thu Mar 04 1915 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat Sep 21 1991 190000 GMT1200 New Zealand Standard Time",
    "Age": "76",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Kaikohe Cemetery Kaikohe RSA Division Block C Plot 347",
    "Place of birth": "Pukekohe or Oue",
    "Place of death": "Whangarei or Kawakawa",
    "AL": "Y",
    "Notes": "Brother of Frederick Richard Underwood, who also served. Husband of Lulu Huirangi Underwood, nee Bryers, who served in the R.N.Z.A.F. Son of Edward (Ted) and Louis (Louie) Levine Underwood, nee Billings, of Rawene. Place of birth: Pukekohe or Oue. Place of death: Whangarei or Kawakawa. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Underwood",
    "Christian Name": "Claude Edgar",
    "Unit": "Inf Bde",
    "Regtl. Number": "26561",
    "Rank": "Pte",
    "Embarkation Dates": "J 41-S 41",
    "Marital Status": "S",
    "Enlistment": "Rotorua",
    "Occupation": "Mill hand",
    "Address": "No 3 Mill, Mokai",
    "Next of Kin": "Mr E Underwood, Rawene f",
    "Date of Birth": "Thu Mar 04 1915 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat Sep 21 1991 190000 GMT1200 New Zealand Standard Time",
    "Age": "76",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Kaikohe Cemetery Kaikohe RSA Division Block C Plot 347",
    "Place of birth": "Pukekohe or Oue",
    "Place of death": "Whangarei or Kawakawa",
    "AL": "Y",
    "Notes": "Brother of Frederick Richard Underwood, who also served. Husband of Lulu Huirangi Underwood, nee Bryers, who served in the R.N.Z.A.F. Son of Edward (Ted) and Louis (Louie) Levine Underwood, nee Billings, of Rawene. Place of birth: Pukekohe or Oue. Place of death: Whangarei or Kawakawa. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Underwood",
    "Christian Name": "Frederick Richard",
    "Unit": "30 Bn",
    "Name Variation": "Underwood, Richard Frederick Fredrick",
    "Regtl. Number": "28317",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Te Kuiti",
    "Occupation": "Grocer",
    "Address": "C o Self Help, Te Kuiti",
    "Next of Kin": "Mr E Underwood, Rawene, Hokianga, f",
    "Date of Birth": "Tue Apr 05 1921 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Tue Feb 04 2003 210000 GMT1300 New Zealand Daylight Time",
    "Age": "81",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Sat Feb 08 2003 21 00 00 GMT 1300 New Zealand Daylight Time",
    "Cemetery/Urupa and Where Known Plot Number": "Hamilton Park Cemetery Hamilton HPC-GOM-FNT-45",
    "Husbands/Wives/Partners": "Mavis Margaret Clow",
    "Place of birth": "Kawakawa",
    "Place of death": "Hamilton",
    "AL": "Y",
    "Notes": "Brother of Claude Edgar Underwood, who also served. Son of Edward (Ted) and (Louis) Louie Levine Underwood, nee Billings. Husband of Mavis Margaret Underwood, nee Clow. Place of birth: Kawakawa. Place of death: Hamilton. Ancestrylibrary.com.au. Familysearch.org"
  },
  {
    "Surname": "Underwood",
    "Christian Name": "Horace",
    "Unit": "35 Bn",
    "Regtl. Number": "286975",
    "Rank": "Pte",
    "Embarkation Dates": "Jan 43- Mar 43",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Farm hand",
    "Address": "Tapuhi, R.D., Hukerenui",
    "Next of Kin": "Mrs A Underwood, Tapuhi, R.D., Hukerenui m",
    "Date of Birth": "Sat May 19 1917 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sun Dec 08 1963 200000 GMT1200 New Zealand Daylight Time",
    "Age": "46",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Otahuhu Cemetery Otahuhu Auckland Area I Lot No 101",
    "Husbands/Wives/Partners": "Ettie Underwood",
    "Place of birth": "Cambridge",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "Brother of Thomas Alfred Underwood, who also served. Son of Henry and Ada Ann Underwood, nee Billing, of Tapuhi, Hukerenui. Husband of Ettie Underwood. Place of birth: Cambridge. Place of death: Auckland. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Underwood",
    "Christian Name": "Thomas Alfred",
    "Unit": "35 Bn",
    "Regtl. Number": "67700",
    "Rank": "Pte",
    "Embarkation Dates": "J-M 42",
    "Marital Status": "M",
    "Enlistment": "Whangarei",
    "Occupation": "Farmer",
    "Address": "Tapuhi, R.D., Hukerenui",
    "Next of Kin": "Mrs M E Underwood, C - Mrs C J Nash, Tapuhi, R.D., Hukerenui w",
    "Date of Birth": "Wed Jun 11 1919 183000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Tue Jul 24 1973 190000 GMT1200 New Zealand Standard Time",
    "Age": "54",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Row Plot 343 Hukerenui",
    "Husbands/Wives/Partners": "Mary Evelyn Nash",
    "Place of birth": "Cambridge",
    "Place of death": "Hukerenui",
    "AL": "Y",
    "Notes": "Brother of Horace Underwood, who served. Son of Henry and Ada Ann Underwood, nee Billing. Husband Mary Evelyn Underwood, nee Nash, per the Marriage Index, of Tapuhi, Hukerenui. Place of birth: Cambridge. Place of death: Hukerenui. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Underwood",
    "Christian Name": "Thomas Alfred",
    "Unit": "35 Bn",
    "Regtl. Number": "67700",
    "Rank": "Pte",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "M",
    "Enlistment": "Whangarei",
    "Occupation": "Farmer",
    "Address": "Tapuhi, R.D., Hukerenui",
    "Next of Kin": "Mrs M E Underwood, C - Mrs C J Nash, Tapuhi, R.D., Hukerenui w",
    "Date of Birth": "Wed Jun 11 1919 183000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Tue Jul 24 1973 190000 GMT1200 New Zealand Standard Time",
    "Age": "54",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Row Plot 343 Hukerenui",
    "Husbands/Wives/Partners": "Mary Evelyn Nash",
    "Place of birth": "Cambridge",
    "Place of death": "Hukerenui",
    "AL": "Y",
    "Notes": "Brother of Horace Underwood, who served. Son of Henry and Ada Ann Underwood, nee Billing. Husband Mary Evelyn Underwood, nee Nash, per the Marriage Index, of Tapuhi, Hukerenui. Place of birth: Cambridge. Place of death: Hukerenui. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Underwood",
    "Christian Name": "Thomas Edward",
    "Unit": "29 Bn",
    "Regtl. Number": "26628",
    "Rank": "T L Cpl",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Dargaville",
    "Occupation": "Storeman",
    "Address": "Mititai",
    "Next of Kin": "Mr W F Underwood, Aratapu, Dargaville f",
    "Where Killed or Died": "West Des",
    "Cemetery Name": "El Alamein War Egypt",
    "Grave/Memorial Reference": "XXVIII D 18",
    "Last rank Held": "Pte",
    "Date of Birth": "Sat Dec 09 1905 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Wed Jul 22 1942 190000 GMT1200 New Zealand Standard Time",
    "Age": "36",
    "Burial/Cremation": "--",
    "AL": "Y",
    "Notes": "Son of William Frederick and Mary Jane Elizabeth Underwood of Arapohue. On the Northern Wairoa RSA WWII Roll of Honour. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Underwood",
    "Christian Name": "Thomas Edward",
    "Unit": "Inf Reinfs",
    "Regtl. Number": "26628",
    "Rank": "T L Cpl",
    "Embarkation Dates": "A 41- J 41",
    "Marital Status": "S",
    "Enlistment": "Dargaville",
    "Occupation": "Storeman",
    "Address": "Mititai",
    "Next of Kin": "Mr W F Underwood, Aratapu, Dargaville f",
    "Where Killed or Died": "West Des",
    "Cemetery Name": "El Alamein War Egypt",
    "Grave/Memorial Reference": "XXVIII D 18",
    "Last rank Held": "Pte",
    "Date of Birth": "Sat Dec 09 1905 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Wed Jul 22 1942 190000 GMT1200 New Zealand Standard Time",
    "Age": "36",
    "Burial/Cremation": "--",
    "AL": "Y",
    "Notes": "Son of William Frederick and Mary Jane Elizabeth Underwood of Arapohue. On the Northern Wairoa RSA WWII Roll of Honour. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Unitt",
    "Christian Name": "William Albert David",
    "Unit": "5 Fd Park Coy",
    "Name Variation": "Unitt, Johnny",
    "Regtl. Number": "3944",
    "Rank": "Spr",
    "Embarkation Dates": "M 40",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Truck Driver",
    "Address": "3 Hill St, Onerahi",
    "Next of Kin": "Mr W S G Unitt, 3 Hill St, Onerahi father",
    "Last rank Held": "Spr",
    "Date of Birth": "Wed May 01 1907 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Thu Jun 19 2003 190000 GMT1200 New Zealand Standard Time",
    "Age": "96",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Thu Dec 11 2003 21 00 00 GMT 1300 New Zealand Daylight Time",
    "Cemetery/Urupa and Where Known Plot Number": "RSA Block Twenty One B Plot 2064 Maunu",
    "Funeral Director": "Morris Morris Whg",
    "Husbands/Wives/Partners": "Edna Florence Nola French",
    "Place of birth": "Plymouth Devon England",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "Son of William Samuel James and Caroline Ann Unitt, nee Hillson, of Onerahi. Husband of Edna Florence (Nola) Unitt, nee French. Place of birth: Plymouth, Devon, England. Place of death: Whangarei. Ancestrylibrary.com.au."
  },
  {
    "Surname": "Upton",
    "Christian Name": "Lawrence John",
    "Unit": "N Z A",
    "Name Variation": "Upton, Jack",
    "Regtl. Number": "70232",
    "Rank": "L Bdr",
    "Embarkation Dates": "J 43- D 43",
    "Marital Status": "M",
    "Enlistment": "Whangarei",
    "Occupation": "Farmhand",
    "Address": "Maungaturoto",
    "Next of Kin": "Mrs G D Upton, C - Staff Division, G.P.O., W'gton w",
    "Date of Birth": "Thu May 16 1918 183000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Wed Oct 26 1949 200000 GMT1200 New Zealand Daylight Time",
    "Age": "31",
    "Cemetery/Urupa and Where Known Plot Number": "Whakapirau Church Cemetery Whakapirau Row 5",
    "Husbands/Wives/Partners": "Gwenith Doreen Bowmar",
    "Place of birth": "NZ",
    "AL": "Y",
    "Notes": "Son of Charles Edward Field and Ada Gertrude Upton, nee Osborne. Husband of Gwenith Doreen Upton, nee Bowmar, of Wellington. Place of birth: New Zealand. Some info on Find a Grave website is incorrect. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Upton",
    "Christian Name": "William Myles",
    "Unit": "30 Bn",
    "Name Variation": "Upton, William Miles",
    "Regtl. Number": "601024",
    "Rank": "Pte",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "W",
    "Enlistment": "Wellington",
    "Occupation": "Labourer",
    "Address": "Dargaville",
    "Next of Kin": "Mr M Upton, Dargaville f",
    "Last rank Held": "Dvr",
    "Date of Birth": "1902",
    "Date of Death": "Wed Mar 08 1967 200000 GMT1200 New Zealand Daylight Time",
    "Age": "65",
    "Cemetery/Urupa and Where Known Plot Number": "New Mount Wesley RSA Cemetery Dargaville RSA Plot no 171",
    "Husbands/Wives/Partners": "Emma Diggle",
    "Place of birth": "New South Wales Australia",
    "Place of death": "Dargaville",
    "AL": "Y",
    "Notes": "Son of Morris Thomas and Anne (Annie) Upton, nee Tencheon, of Dargaville. Husband of Emma Upton, nee Diggle. Place of birth: New South Wales, Australia. Place of death: Dargaville. William Miles Upton is as per the Death Index. Age is possibly 63 at death. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Ure",
    "Christian Name": "Alfred William",
    "Unit": "37 Bn",
    "Regtl. Number": "50572",
    "Rank": "Pte",
    "Embarkation Dates": "J-M 42",
    "Marital Status": "S",
    "Enlistment": "Invercargill",
    "Occupation": "Farm hand",
    "Address": "C - R Sinclair, Dipton",
    "Next of Kin": "Mr B B Ure, 136 Liddel St, Inver'gill f",
    "Date of Birth": "Thu Apr 24 1919 183000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Dec 17 1973 200000 GMT1200 New Zealand Standard Time",
    "Age": "54",
    "Cemetery/Urupa and Where Known Plot Number": "Riversdale Cemetery Riversdale Southland 53 Block XVII and 54",
    "Husbands/Wives/Partners": "Gladys Marion Marion Robertson",
    "Place of death": "Gore",
    "AL": "Y",
    "Notes": "Son of Robert William Brown and Ellen Jane Ure. Husband of Gladys Marion (Marion) Ure, nee Robertson. Place of death: Gore. Father s initials are B B in the NOK details. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Ure",
    "Christian Name": "Alfred William",
    "Unit": "37 Bn",
    "Regtl. Number": "50572",
    "Rank": "T L Cpl",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "S",
    "Enlistment": "Dargaville",
    "Occupation": "Farm hand",
    "Address": "C - R Sinclair, Dipton",
    "Next of Kin": "Mr B B Ure, 136 Liddel St, Inver'gill f",
    "Date of Birth": "Thu Apr 24 1919 183000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Dec 17 1973 200000 GMT1200 New Zealand Standard Time",
    "Age": "54",
    "Cemetery/Urupa and Where Known Plot Number": "Riversdale Cemetery Riversdale Southland 53 Block XVII and 54",
    "Husbands/Wives/Partners": "Gladys Marion Marion Robertson",
    "Place of death": "Gore",
    "AL": "Y",
    "Notes": "Son of Robert William Brown and Ellen Jane Ure. Husband of Gladys Marion (Marion) Ure, nee Robertson. Place of death: Gore. Father s initials are B B in the NOK details. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Urlich",
    "Christian Name": "Daniel",
    "Unit": "28 Maori",
    "Name Variation": "Urlich, Dan",
    "Regtl. Number": "1362",
    "Rank": "2 Lt",
    "Embarkation Dates": "J 40",
    "Marital Status": "M",
    "Enlistment": "Kaitaia",
    "Occupation": "Storekeeper and truck contract",
    "Address": "Rural Delivery, Kaitaia",
    "Next of Kin": "Mrs Ruby Ann Beryl Urlich, Kaiaka, Kaitaia Rural Mail Delivery",
    "Last rank Held": "Capt",
    "Date of Birth": "Wed Oct 07 1914 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sun Nov 19 1961 200000 GMT1200 New Zealand Daylight Time",
    "Age": "47",
    "Cemetery/Urupa and Where Known Plot Number": "Mangere Lawn Cemetery Mangere Auckland",
    "Husbands/Wives/Partners": "Ruby Ann Beryl Christensen",
    "Place of birth": "NZ",
    "AL": "Y",
    "Notes": "Brother of Ivan James and Stephen Henry Urlich, who also served and Joseph John Urlich, who served in the R.N.Z.N., and fell. Son of Ivan James (James Ivan) (Jim) and (Huriata) Julia Urlich, nee Porter (Poata), of Kaitaia. Husband of Ruby Ann Beryl Urlich, nee Christensen. Place of birth: New Zealand. Memories on Maori Battalion website. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Urlich",
    "Christian Name": "Ivan James",
    "Unit": "28 Maori",
    "Regtl. Number": "62787",
    "Rank": "Pte",
    "Embarkation Dates": "A 41- J 41",
    "Marital Status": "S",
    "Enlistment": "Kaitaia",
    "Occupation": "Truck driver",
    "Address": "R.D., Kaitaia",
    "Next of Kin": "Mrs J Urlich, R.D., Kaitaia m",
    "Last rank Held": "Pte",
    "Date of Birth": "Tue Nov 21 1922 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Thu Mar 10 1983 200000 GMT1200 New Zealand Standard Time",
    "Age": "60",
    "Cemetery/Urupa and Where Known Plot Number": "Mangere Lawn Cemetery Mangere Auckland",
    "Husbands/Wives/Partners": "Dolly Elizabeth Urlich Huriata Poata",
    "Place of birth": "Matangirau Kaeo",
    "Place of death": "Mangere Auckland",
    "AL": "Y",
    "Notes": "Brother of Daniel and Stephen Henry Urlich, who also served and Joseph John Urlich, who served in the R.N.Z.N., and fell. Son of Ivan James (James Ivan) (Jim) and (Huriata) Julia Urlich, nee Porter, (Poata) of Kaitaia. Husband of Dolly Elizabeth Urlich. Husband of Huriata Urlich, nee Poata. Memories on Maori Battalion website. Listed as wounded in Evening Post 2 Jan 1942. Not on Auckland cemetery index. Plot no., is unknown. Geni.com. Possibly born in 1923. Place of birth: Matangirau, Kaeo. Place of death: Mangere, Auckland. Ivan Urlich is as per the Birth Index. Writing on gravestone is not clearly legible. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Urlich",
    "Christian Name": "Pomare",
    "Unit": "28 Maori",
    "Regtl. Number": "62706",
    "Rank": "Pte",
    "Embarkation Dates": "A 41- J 41",
    "Marital Status": "S",
    "Enlistment": "Rotorua",
    "Occupation": "Public Works Department employee",
    "POW": "Y",
    "Place of capture": "Unknown",
    "Address": "Taupo",
    "Next of Kin": "Mr P Urlich, Whangaroa f",
    "Last rank Held": "Pte",
    "Date of Birth": "Fri Feb 16 1917 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat Dec 20 2008 210000 GMT1300 New Zealand Daylight Time",
    "Age": "91",
    "Husbands/Wives/Partners": "Te Aue Lucy Poata",
    "Place of birth": "Northland",
    "Place of death": "Whangaroa",
    "AL": "Y",
    "Notes": "POW. Son of Petar (Peter) Urlic (Urlich) and Hiria Urlich, nee Paraone Hoori, of Whangaroa. Husband of Te Aue Lucy Urlich, nee Poata. Memories on Maori Battalion website. Place of birth: Northland. Place of death: Whangaroa. Geni.com. Ancestrylibrary.com"
  },
  {
    "Surname": "Urlich",
    "Christian Name": "Stephen Henry",
    "Unit": "28 Maori",
    "Name Variation": "Urlich, Steve Henry",
    "Regtl. Number": "68246",
    "Rank": "2 Lt",
    "Embarkation Dates": "A 43-J 43",
    "Marital Status": "S",
    "Enlistment": "Kaitaia",
    "Occupation": "Carrier",
    "Address": "Kaitaia, R.D.",
    "Next of Kin": "Mrs T Urlich, Kaitaia, R.D. m",
    "Last rank Held": "Capt",
    "Date of Birth": "Wed Feb 21 1917 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Wed Sep 11 1991 190000 GMT1200 New Zealand Standard Time",
    "Age": "74",
    "Cemetery/Urupa and Where Known Plot Number": "Mangere Lawn Cemetery Mangere Auckland",
    "Husbands/Wives/Partners": "Phoebe Lilian Urlich",
    "Place of birth": "Whangaroa",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "Brother of Daniel and Ivan James Urlich, who also served and Joseph John Urlich, who served in the R.N.Z.N., and fell. Son of (James) Ivan (Jim) (Ivan James) and (Huriata) Julia Urlich, nee Porter, (Poata), of Kaitaia. Husband of Phoebe Lilian Urlich. Mother s initial is T in the NOK details. Memories on Maori Battalion website. Steve Henry Urlich on the Birth Index. On the RSA Point Chevalier Memorial Panel. Place of birth: Whangaroa. Place of death: Auckland. Plot number is unknown. Geni.com. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Urquhart",
    "Christian Name": "Alexander Lorne",
    "Unit": "N Z A",
    "Regtl. Number": "265537",
    "Rank": "Gnr",
    "Embarkation Dates": "J 44-M 44",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Farmer",
    "Address": "Taurikura",
    "Next of Kin": "Mr A D Urquhart, Whangarei, R.D. f",
    "Date of Birth": "Wed Jan 01 1919 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Wed Aug 28 1996 190000 GMT1200 New Zealand Standard Time",
    "Age": "77",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Fri Aug 30 1996 19 00 00 GMT 1200 New Zealand Standard Time",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Newberrys Whg",
    "Husbands/Wives/Partners": "Jill Trimmer",
    "Place of birth": "Whangarei",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "Son of Alexander Alex Donald and Sarah Sassie Urquhart, nee McFadyen, of Whangarei. Husband of Jill Urquhart, nee Trimmer. Cremated at Maunu Cemetery & Crematorium, Whangarei; no other information. Place of birth and death: Whangarei. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Urwin",
    "Christian Name": "Arthur Francis",
    "Unit": "Inf Bde",
    "Regtl. Number": "65113",
    "Rank": "Pte",
    "Embarkation Dates": "J 41-S 41",
    "Marital Status": "M",
    "Enlistment": "Kaitaia",
    "Occupation": "Labourer",
    "POW": "Y",
    "Place of capture": "Italy",
    "Address": "P O Waihopo",
    "Next of Kin": "Mrs M M Urwin, P O Waihopo w",
    "Where Killed or Died": "Italy",
    "Cemetery Name": "Caserta War Italy",
    "Grave/Memorial Reference": "VI C 4",
    "Last rank Held": "Pte",
    "Date of Birth": "Tue Oct 03 1911 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Wed Aug 26 1942 190000 GMT1200 New Zealand Standard Time",
    "Age": "30",
    "Burial/Cremation": "--",
    "Husbands/Wives/Partners": "Mary Melba Ford",
    "Place of birth": "Waihopo",
    "AL": "Y",
    "Notes": "POW. Son of Francis Victor 'Frank' and Maud Eva 'Doris' Urwin, nee Tynan. of Waihopo. Husband of Mary Melba Urwin, nee Ford, per the Marriage Index, of Waihopo. Place of birth: Waihopo. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Urwin",
    "Christian Name": "William John",
    "Unit": "24 Auck",
    "Regtl. Number": "24350",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Kaikohe",
    "Occupation": "Motor-driver",
    "Address": "C - N Z Railways, Kaikohe",
    "Next of Kin": "Mrs J Urwin, C - N Z Railways, Kaikohe m",
    "Last rank Held": "Cpl",
    "Date of Birth": "Wed Sep 15 1920 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Tue Oct 22 2002 200000 GMT1300 New Zealand Daylight Time",
    "Age": "82",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Aramoho Cemetery Wanganui Plot 416 Aramoho RSA Lawn C 7",
    "Funeral Director": "Ballard Cleveland Ltd",
    "Husbands/Wives/Partners": "Nyla Joyce Urwin",
    "Place of birth": "Thomastown Kildare Ireland",
    "Place of death": "Wanganui",
    "AL": "Y",
    "Notes": "Son of Jack Harman and Julia Urwin, of Kaikohe. Husband of Nyla Joyce Urwin. Date of death wrong on Cenotaph database. Bio on the database. Place of birth: Thomastown, Kildare, Ireland. He appears in the Birth Index. Last address 31B Liffiton Street, Wanganui. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Urwin",
    "Christian Name": "William John",
    "Unit": "N Z M C",
    "Regtl. Number": "24350",
    "Rank": "Pte",
    "Embarkation Dates": "J 44-M 44",
    "Marital Status": "S",
    "Enlistment": "Kaikohe",
    "Occupation": "Motor-driver",
    "Address": "N Z R, Kaikohe",
    "Next of Kin": "Mrs J Urwin, N Z R, Kaikohe m",
    "Last rank Held": "Cpl",
    "Date of Birth": "Wed Sep 15 1920 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Tue Oct 22 2002 200000 GMT1300 New Zealand Daylight Time",
    "Age": "82",
    "Cemetery/Urupa and Where Known Plot Number": "Aramoho Cemetery Wanganui Plot 416 Aramoho RSA Lawn C 7",
    "Funeral Director": "Ballard Cleveland Ltd",
    "Husbands/Wives/Partners": "Nyla Joyce Urwin",
    "Place of birth": "Thomastown Kildare Ireland",
    "Place of death": "Wanganui",
    "AL": "Y",
    "Notes": "Son of Jack Harman and Julia Urwin, of Kaikohe. Husband of Nyla Joyce Urwin. Date of death wrong on Cenotaph database. Bio on the database. Place of birth: Thomastown, Kildare, Ireland. He appears in the Birth Index. Last address 31B Liffiton Street, Wanganui. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Utting",
    "Christian Name": "Gordon Noel",
    "Unit": "36 Bn",
    "Regtl. Number": "72183",
    "Rank": "2 Lt",
    "Embarkation Dates": "A 42-J 42",
    "Marital Status": "M",
    "Enlistment": "Auckland",
    "Occupation": "School Teacher",
    "Address": "59 Prospect Tce, Mt. Eden, Auck.",
    "Next of Kin": "Mrs G M Utting, C o Mrs W N Hunter, P O Box 9, Bombay w",
    "Last rank Held": "Mjr",
    "Date of Birth": "Sun Jan 02 1910 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Tue Nov 25 1980 210000 GMT1300 New Zealand Daylight Time",
    "Age": "70",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Kawakawa Cemetery RSA Division Block 9A Plot 45",
    "Funeral Director": "Morris Morris Funeral Home",
    "Husbands/Wives/Partners": "Gwenda Marian Morris",
    "Place of birth": "Auckland",
    "Place of death": "Northland Base Hospital Whangarei",
    "AL": "Y",
    "Notes": "ED. Husband of Gwenda Marian Utting, nee Morris, per the Marriage Index, who served in the WAAC. Son of Walter Ernest and Violet Isabel Utting, nee Kelly. Place of death: Northland Base Hospital, Whangarei. Place of birth: Auckland. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Utting",
    "Christian Name": "Gordon Noel",
    "Unit": "36 Bn",
    "Regtl. Number": "72183",
    "Rank": "2 Lt",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "M",
    "Enlistment": "Auckland",
    "Occupation": "School Teacher",
    "Address": "59 Prospect Tce, Mt. Eden, Auck.",
    "Next of Kin": "Mrs G M Utting, C o Mrs W N Hunter, P O Box 9, Bombay w",
    "Last rank Held": "Mjr",
    "Date of Birth": "Sun Jan 02 1910 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Tue Nov 25 1980 210000 GMT1300 New Zealand Daylight Time",
    "Age": "70",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Kawakawa Cemetery RSA Division Block 9A Plot 45",
    "Funeral Director": "Morris Morris Funeral Home",
    "Husbands/Wives/Partners": "Gwenda Marian Morris",
    "Place of birth": "Auckland",
    "Place of death": "Northland Base Hospital Whangarei",
    "AL": "Y",
    "Notes": "ED. Husband of Gwenda Marian Utting, nee Morris, per the Marriage Index, who served in the WAAC. Son of Walter Ernest and Violet Isabel Utting, nee Kelly. Place of death: Northland Base Hospital, Whangarei. Place of birth: Auckland. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Utting",
    "Christian Name": "Gordon Noel",
    "Unit": "Inf Bde",
    "Regtl. Number": "72183",
    "Rank": "Lt",
    "Embarkation Dates": "J 43- D 43",
    "Marital Status": "M",
    "Enlistment": "Auckland",
    "Occupation": "School Teacher",
    "Address": "59 Prospect Tce, Mt. Eden, Auck.",
    "Next of Kin": "Mrs G M Utting, C o Mrs W N Hunter, P O Box 9, Bombay w",
    "Last rank Held": "Mjr",
    "Date of Birth": "Sun Jan 02 1910 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Tue Nov 25 1980 210000 GMT1300 New Zealand Daylight Time",
    "Age": "70",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Kawakawa Cemetery RSA Division Block 9A Plot 45",
    "Funeral Director": "Morris Morris Funeral Home",
    "Husbands/Wives/Partners": "Gwenda Marian Morris",
    "Place of birth": "Auckland",
    "Place of death": "Northland Base Hospital Whangarei",
    "AL": "Y",
    "Notes": "ED. Husband of Gwenda Marian Utting, nee Morris, per the Marriage Index, who served in the WAAC. Son of Walter Ernest and Violet Isabel Utting, nee Kelly. Place of death: Northland Base Hospital, Whangarei. Place of birth: Auckland. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Utting",
    "Christian Name": "Gordon Noel",
    "Unit": "Inf Reinfs",
    "Regtl. Number": "72183",
    "Rank": "Lt",
    "Embarkation Dates": "J 45-D 45",
    "Marital Status": "M",
    "Enlistment": "Auckland",
    "Occupation": "School Teacher",
    "Address": "59 Prospect Tce, Mt. Eden, Auck.",
    "Next of Kin": "Mrs G M Utting, C o Mrs W N Hunter, P O Box 9, Bombay w",
    "Last rank Held": "Mjr",
    "Date of Birth": "Sun Jan 02 1910 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Tue Nov 25 1980 210000 GMT1300 New Zealand Daylight Time",
    "Age": "70",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Kawakawa Cemetery RSA Division Block 9A Plot 45",
    "Funeral Director": "Morris Morris Funeral Home",
    "Husbands/Wives/Partners": "Gwenda Marian Morris",
    "Place of birth": "Auckland",
    "Place of death": "Northland Base Hospital Whangarei",
    "AL": "Y",
    "Notes": "ED. Husband of Gwenda Marian Utting, nee Morris, per the Marriage Index, who served in the WAAC. Son of Walter Ernest and Violet Isabel Utting, nee Kelly. Place of death: Northland Base Hospital, Whangarei. Place of birth: Auckland. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Uttley",
    "Christian Name": "Leslie McNeill",
    "Unit": "20 Canto",
    "Name Variation": "Uttley, Leslie McNeil Uttley, Buster",
    "Regtl. Number": "8335",
    "Rank": "T Cpl",
    "Embarkation Dates": "M 40",
    "Marital Status": "S",
    "Enlistment": "Invercargill",
    "Occupation": "Civil servant",
    "POW": "Y",
    "Place of capture": "Unknown",
    "Address": "339 Crinan St, Invercargill",
    "Next of Kin": "Mrs G H Uttley, 339 Crinan St, Invercargill m",
    "Date of Birth": "Tue Jan 18 1916 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Thu Sep 20 1984 190000 GMT1200 New Zealand Standard Time",
    "Age": "68",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Onerahi Cemetery Whangarei I Plot 14",
    "Funeral Director": "Morris Morris Whg",
    "Husbands/Wives/Partners": "Jesslie Pearl Cameron",
    "Place of birth": "NZ or Victoria Australia",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "POW. Son of George Harry and Elizabeth Loudon Uttley, nee McNeill, of Invercargill. Husband of Jesslie Pearl Uttley, nee Cameron. Affectionately known as 'Buster'. On the Death Index and cemetery record name is shown as Leslie McNeil Uttley. Place of birth: either Victoria, Australia, or New Zealand. Place of death: Whangarei. Geni.com. Myheritage.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Ututaonga",
    "Christian Name": "Paratene Dan",
    "Unit": "28 Maori",
    "Name Variation": "Ututaonga, Paratene Ututaonga, Paratone",
    "Regtl. Number": "67661",
    "Rank": "Pte",
    "Embarkation Dates": "J 41-S 41",
    "Marital Status": "M",
    "Enlistment": "Kaikohe",
    "Occupation": "Labourer",
    "Address": "Oromahoe, Pakaraka",
    "Next of Kin": "Mrs M A Ututaonga, Pakaraka w",
    "Last rank Held": "Pte",
    "Date of Birth": "Sat Nov 20 1909 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat Apr 30 1955 190000 GMT1200 New Zealand Standard Time",
    "Age": "45",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Husbands/Wives/Partners": "Mere Atarangi Tane",
    "Place of birth": "Taumarere Kawakawa",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "Brother of Wally (Walter) William (Wiremu Whare) and Bill Isaac (Wiremu Bill Ututaonga), who also served. Son of Wiremu Ihaka Te Herehere and Ngakirikiri Hone Ututaonga, nee Cherrington-Keretene. Husband of Mere Atarangi Ututaonga, nee Tane, of Pakaraka. Paratone Ututaonga is on the Death Index. Buried at Oramahoe. Geni.com. Place of birth: Taumarere, Kawakawa. Place of death: Auckland. Myheritage.com. Credit Ronboy Ututaonga. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Ututaonga",
    "Christian Name": "Wally William",
    "Unit": "Maori Bn",
    "Name Variation": "Ututaonga, Walter William Ututaonga, Walter Wiremu Ututaonga, Whare",
    "Regtl. Number": "68056",
    "Rank": "Cpl",
    "Embarkation Dates": "A 43-J 43",
    "Marital Status": "S",
    "Enlistment": "Kawakawa",
    "Occupation": "Labourer",
    "Address": "Opua",
    "Next of Kin": "Mr H Ututaonga, Opua f",
    "Last rank Held": "Cpl",
    "Date of Birth": "Thu Feb 05 1920 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Mon Jan 23 1984 210000 GMT1300 New Zealand Daylight Time",
    "Age": "63",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Kauae Cemetery Rotorua Block 9 Section M80 Plot 1",
    "Husbands/Wives/Partners": "Lynne Rauora Whanaupani Pihama-Bishop",
    "Place of birth": "Taumarere",
    "Place of death": "Rotorua",
    "AL": "Y",
    "Notes": "Brother of Bill Isaac (Wiremu Bill Ututaonga) and Paratene (Dan) Ututaonga, who also served. Son of Wiremu Ihaka Te Herehere and Ngakirikiri Hone Ututaonga, nee Cherrington-Keretene. Husband of Lynne Rauora Whanaupani Ututaonga, nee Pihama-Bishop. Father s initial is shown as H in the NOK details. On the Cenotaph Database in the name of Walter William Ututaonga. Place of birth: Taumarere. Place of death: Rotorua. Credit Ronboy Ututaonga. Geni.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Ututaonga",
    "Christian Name": "Wiremu Bill",
    "Unit": "28 Maori",
    "Name Variation": "See under Issac, Bill Isaac, Wiremu Bill",
    "Regtl. Number": "39669",
    "Rank": "Pte",
    "Embarkation Dates": "J 40",
    "Marital Status": "S",
    "Enlistment": "Kaikohe",
    "Occupation": "Labourer",
    "Address": "Pakaraka",
    "Next of Kin": "Mr D Ututaonga, Pakaraka b",
    "Last rank Held": "Pte",
    "Date of Birth": "Sun Feb 18 1923 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Wed Sep 03 1980 190000 GMT1200 New Zealand Standard Time",
    "Age": "57",
    "Husbands/Wives/Partners": "Lorraine Mary Bligh Parker",
    "Place of birth": "Taumarere Kawakawa",
    "Place of death": "Christchurch or Auckland",
    "AL": "Y",
    "Notes": "Brother of Paratene (Dan) and Wally (Walter) William (William Whare) Ututaonga, who also served. Son of Wiremu Ihaka Te HereHere and Ngakirikiri Ututaonga, nee Cherrington-Keretene). Husband of Lorraine Mary Bligh Isaac, nee Parker. Brother of Mr D Ututaonga, of Pakaraka. Place of birth: Taumarere, Kawakawa. Place of death: Christchurch or Auckland. Geni.com. MyHeritage.com. Ancestrylibrary.com.au"
  }
];