const veteransDataY = [
  {
    "Surname": "Yakas",
    "Christian Name": "Ivan",
    "Unit": "H Q Inf Corps",
    "Regtl. Number": "812815",
    "Rank": "Pte",
    "Embarkation Dates": "Jan 46-Jun 48",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Flax mill hand",
    "Address": "P O Box 51, Dargaville",
    "Next of Kin": "Mrs K Yakas, P O Box 51, Dargaville m",
    "Date of Birth": "Sat May 08 1926 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Wed Jul 10 2019 190000 GMT1200 New Zealand Standard Time",
    "Age": "93",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Mt Wesley Cemetery Dargaville",
    "Husbands/Wives/Partners": "Judy Yakas",
    "Place of birth": "Dargaville",
    "Place of death": "Dargaville Hospital Dargaville",
    "AL": "Y",
    "Notes": "Brother of James (Yakov) Yakas, who also served. Son of Anton and Kata Yakas, nee Batistic, of Dargaville. Husband of Judy Yakas. Bereavement notice in Northern Advocate 12 July, 2019. Place of birth: Dargaville. Place of death: Dargaville Hospital, Dargaville. Plot no. Is unknown. Geni.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yakas",
    "Christian Name": "James",
    "Unit": "Inf Corps",
    "Name Variation": "Yakas, Yakov Yakas, Jim",
    "Regtl. Number": "639563",
    "Rank": "Pte",
    "Embarkation Dates": "Jan 46-Jun 48",
    "Marital Status": "M",
    "Enlistment": "Whangarei",
    "Occupation": "Farm hand",
    "Address": "Hoanga, Dargaville",
    "Next of Kin": "Mrs L Yakas, Hoanga, Dargaville w",
    "Date of Birth": "Mon Aug 12 1912 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Feb 08 1993 210000 GMT1300 New Zealand Daylight Time",
    "Age": "80",
    "Cemetery/Urupa and Where Known Plot Number": "Mt Wesley Cemetery Old Dargaville",
    "Husbands/Wives/Partners": "Connie Yakas Louisa Harriet May Franklin",
    "Place of birth": "Zyrnova Korcula Yugoslavia",
    "Place of death": "Dargaville",
    "AL": "Y",
    "Notes": "Brother of Ivan Yakas, who also served. Son of Anton (Antun) and Kata Yakas, nee Batistic, of Dargaville. Husband of Connie Yakas, of Hoanga. Husband of Louisa (Louise) Harriet May Yakas, nee Franklin. Wife shown as Mrs L Yakas, of Hoanga, in the NOK details. Presumed to be this person. Place of birth: Zyrnova, Korcula, Yugoslavia. Place of death: Dargaville. Plot no. Is unknown. Geni.com. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yakas",
    "Christian Name": "William Nicholas",
    "Unit": "29 Lt A A",
    "Name Variation": "Yakas, Bill",
    "Regtl. Number": "602026",
    "Rank": "Gnr",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "M",
    "Enlistment": "Rawene",
    "Occupation": "Dairy farmer",
    "Address": "Opononi",
    "Next of Kin": "Mrs C R Yakas, Rawene, R.M.D. w",
    "Date of Birth": "Tue Oct 08 1918 183000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Fri Dec 28 1984 210000 GMT1300 New Zealand Daylight Time",
    "Age": "66",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Husbands/Wives/Partners": "Catherine Katherine Rita Williams Baker",
    "Place of birth": "Waipoua Hokianga or Waimamaku",
    "Place of death": "Opononi or Waimamaku",
    "AL": "Y",
    "Notes": "Son of Nikola Marin and Te Miringa Yakas, nee Morunga. Husband of Catherine (Katherine) Rita Williams Yakas, nee Baker, of Rawene. Possibly Nicholas Yakas who is listed on Billiongraves.com. Buried at Mt. Wesley, Dargaville? Place of birth: Waipoua, Hokianga, or Waimamaku. Place of death: Opononi or Waimamaku. Geni.com. Ancestors.familysearch.org. Myheritage.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yanko",
    "Christian Name": "Andrew Quenton",
    "Unit": "2 Div Sigs",
    "Name Variation": "Yanko, Andrew Quinton",
    "Regtl. Number": "4762",
    "Rank": "Sgmn",
    "Embarkation Dates": "M 40",
    "Marital Status": "M",
    "Enlistment": "Kaikohe",
    "Occupation": "Linesman",
    "Address": "Kaikohe",
    "Next of Kin": "Mrs J M Yanko, Victoria Valley, Kaitaia w",
    "Date of Birth": "Wed Jan 11 1905 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Wed Oct 21 1964 190000 GMT1200 New Zealand Daylight Time",
    "Age": "59",
    "Cemetery/Urupa and Where Known Plot Number": "Hamilton Park Cemetery Hamilton New Zealand RSA-02-085",
    "Husbands/Wives/Partners": "Jessie Myrtle Panther",
    "Place of birth": "Waitotara Taranaki",
    "Place of death": "Hamilton",
    "AL": "Y",
    "Notes": "MID. Son of John (Johan) and Elizabeth Jane (Lizzie) Yanko, (Janko), nee Richmond. Husband of Jessie Myrtle Yanko, nee Panther, of Victoria Valley, Kaitaia. MyHeritage.com has mother named as Caterina Yanko. Place of birth: Waitotara, Taranaki. Place of death: Hamilton. Birth record shows name as Andrew Quinton Yanko. Myheritage.com. Geni.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yates",
    "Christian Name": "Arthur Robert",
    "Unit": "N Z E",
    "Name Variation": "Yates, Bob",
    "Regtl. Number": "606619",
    "Rank": "Spr",
    "Embarkation Dates": "J 43- D 43",
    "Marital Status": "M",
    "Enlistment": "Kaitaia",
    "Occupation": "Farmer",
    "Address": "Private Bag, Mangonui",
    "Next of Kin": "Mrs M I Yates, Kaitaia, R.D. w",
    "Date of Birth": "Thu Feb 16 1911 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat Jan 15 1983 210000 GMT1300 New Zealand Daylight Time",
    "Age": "71",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Kaitaia Cemetery Kaitaia RSA Division Plot 232",
    "Funeral Director": "Geards Funeral Home",
    "Husbands/Wives/Partners": "Marjorie Innes Forsyth",
    "Place of birth": "Houhora",
    "Place of death": "Taipa",
    "AL": "Y",
    "Notes": "Brothers Brown Gustavus, Edward Lewis and Samuel Yates also served. Son of Gustavus Gussie Timoti (Timothy) and Emily Yates, nee Bartley, (Bartlett), of Kaitaia. Husband of Marjorie Innes Yates, nee Forsyth, per the Marriage Index, of Kaitaia. Place of birth: Houhora. Place of death: Taipa. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yates",
    "Christian Name": "Brown Gustavus",
    "Unit": "2 Div Arty",
    "Name Variation": "Yates, Brown Gustuvus Yates, Brown Gustuvas",
    "Regtl. Number": "30364",
    "Rank": "Sgt",
    "Embarkation Dates": "J 44-M 44",
    "Marital Status": "S",
    "Enlistment": "Tolaga Bay",
    "Occupation": "Farm hand",
    "Address": "Mangatieia Stn, Tolaga Bay",
    "Next of Kin": "Mrs E Yates, Kaitaia, R.D. m",
    "Date of Birth": "Sat Feb 01 1913 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Tue Feb 19 2008 210000 GMT1300 New Zealand Daylight Time",
    "Age": "95",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Fri Feb 22 2008 21 00 00 GMT 1300 New Zealand Daylight Time",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Jones Company Funeral Services",
    "Place of death": "Mt Maunganui Tauranga",
    "AL": "Y",
    "Notes": "Brothers Arthur Robert, Edward Lewis and Samuel Yates also served. Son of Gustavus Gussie Timoti (Timothy) and Emily Yates, nee Bartley, (Bartlett), of Kaitaia. Service at Mt. Maunganui. Place of death: Mt. Maunganui, Tauranga. Cremated. Death index and cemetery record in the name of Brown Gustuvas Yates. Cremated at Pyes Pa Cemetery & Crematorium, Tauranga. No other information. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yates",
    "Christian Name": "Edward Lewis",
    "Unit": "18 Auck",
    "Name Variation": "Yates, Ted",
    "Regtl. Number": "3855",
    "Rank": "Pte",
    "Embarkation Dates": "M 40",
    "Marital Status": "M",
    "Enlistment": "Auckland",
    "Occupation": "Labourer",
    "Address": "Weymouth, Manurewa, Auckland",
    "Next of Kin": "Mrs D E Yates, Weymouth, Manurewa, Auckland wife",
    "Date of Birth": "Sat Jan 26 1901 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Tue Apr 26 1988 190000 GMT1200 New Zealand Standard Time",
    "Age": "87",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Fri Apr 29 1988 19 00 00 GMT 1200 New Zealand Standard Time",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Sibuns Funeral Advisors",
    "Husbands/Wives/Partners": "Doris Emily Carr",
    "Place of birth": "Paua Parengarenga",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "Brothers Arthur Robert, Brown Gustavus and Samuel Yates also served. Son of Gustavus Gussie Timoti (Timothy) and Emily Yates, nee Bartley, (Bartlett). Of Kaitaia. Husband of Doris Emily Yates, nee Carr, per the Marriage Index, of Manurewa. Place of birth: Paua, Parengarenga. Place of death: Auckland. Some information received from John Garton. Cremated at Purewa Crematorium, Meadowbank, Auckland. Ashes scattered. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yates",
    "Christian Name": "Keith Edward",
    "Unit": "2 Div Cav",
    "Name Variation": "Yates, Keith Edwards",
    "Regtl. Number": "12075",
    "Rank": "Tpr",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Kaitaia",
    "Occupation": "Casual labourer",
    "Address": "Herekino",
    "Next of Kin": "Mrs M Yates, Herekino m",
    "Date of Birth": "Tue Jun 22 1915 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Fri Dec 06 1996 210000 GMT1300 New Zealand Daylight Time",
    "Age": "81",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Sat Jun 20 2015 19 00 00 GMT 1200 New Zealand Standard Time",
    "Cemetery/Urupa and Where Known Plot Number": "Mangatainoka Pahiatua Cemetery Mangatainoka Lawn Ashes Section Block 3 Plot 21 Grave 28",
    "Funeral Director": "Tararua Funeral Services Ltd",
    "Husbands/Wives/Partners": "Lilian Dora Connell",
    "Place of birth": "Ahipara",
    "Place of death": "Napier",
    "AL": "Y",
    "Notes": "Brother of Vayne Edgerton Yates, who also served, with the R.N.Z.N. Son of Egerton and Mabel Reid Yates. Husband of Lilian Dora Yates, nee Connell. Keith Yates is recorded on the Birth index. Keith Edwards Yates is on the burial record. Place of birth: Ahipara. Place of death: Napier. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yates",
    "Christian Name": "Leslie Donald",
    "Unit": "2 Div Sigs",
    "Regtl. Number": "31874",
    "Rank": "Sgmn",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Greymouth",
    "Occupation": "Labourer",
    "Address": "Dobson Station",
    "Next of Kin": "Mrs C Yates, Whangarei mother",
    "Date of Birth": "Sat Aug 20 1910 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Wed Nov 16 1983 210000 GMT1300 New Zealand Daylight Time",
    "Age": "73",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Fri Nov 18 1983 21 00 00 GMT 1300 New Zealand Daylight Time",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Unknown",
    "Husbands/Wives/Partners": "Irene Mary Nelson",
    "Place of birth": "NZ",
    "AL": "Y",
    "Notes": "Son of Mrs C Yates, of Whangarei. Husband of Irene Mary Yates, nee Nelson. Parents are possibly Thomas and Cecy Maria Yates, per FAG. On the North cemetery Index. Ashes returned to family. Place of birth: New Zealand. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yates",
    "Christian Name": "Samuel",
    "Unit": "24 Auck",
    "Regtl. Number": "24393",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "M",
    "Enlistment": "Kaitaia",
    "Occupation": "Labourer",
    "Address": "Rural Delivery 111, Kaitaia",
    "Next of Kin": "Mrs A Yates, Peria w",
    "Last rank Held": "Pte",
    "Date of Birth": "Tue Aug 22 1905 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Fri Apr 08 1966 200000 GMT1200 New Zealand Standard Time",
    "Age": "60",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Kaitaia Cemetery RSA Division Plot 70",
    "Funeral Director": "Geards Funeral Home",
    "Husbands/Wives/Partners": "Adelaide Lallie Moorhouse",
    "Place of birth": "Auckland",
    "Place of death": "Greenlane Hospital Auckland",
    "AL": "Y",
    "Notes": "DCM. MID. Brothers Arthur Robert, Brown Gustavus and Edward Lewis Yates, also served. Son of Gustavus Gussie Timoti (Timothy) and Emily Yates, nee Bartley, (Bartlett), of Kaitaia. Husband of Adelaide Lallie Yates, nee Moorhouse, per the Marriage Index, of Peria. Place of birth: Auckland. Place of death: Greenlane Hospital, Auckland. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yates",
    "Christian Name": "Tai",
    "Unit": "28 Maori",
    "Name Variation": "Yates, Taihaupapa Yates, Tai-Haupapa",
    "Regtl. Number": "1365",
    "Rank": "Cpl",
    "Embarkation Dates": "J 40",
    "Marital Status": "M",
    "Enlistment": "Kaitaia",
    "Occupation": "Butcher",
    "Address": "Awanui",
    "Next of Kin": "Mrs Patricia Yates, Awanui, near Otiria w",
    "Last rank Held": "Lt",
    "Date of Birth": "Fri Apr 03 1914 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Tue Aug 12 1980 190000 GMT1200 New Zealand Standard Time",
    "Age": "66",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Kaitaia Cemetery RSA Division Plot 220",
    "Funeral Director": "Unknown",
    "Husbands/Wives/Partners": "Patricia Myra Patty Smith",
    "Place of birth": "NZ",
    "Place of death": "Whangarei Hospital Whangarei",
    "AL": "Y",
    "Notes": "Son of Lancelot Adolphus and Jane Heeni Yates, nee Murray. Husband of Patricia Myra (Patty) Yates, nee Smith, per the Marriage Index, of Awanui. Place of birth: New Zealand. Place of death: Whangarei Hospital, Whangarei. Taihaupapa Yates is as per the Death Index. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yearbury",
    "Christian Name": "James William",
    "Unit": "Inf Bde",
    "Regtl. Number": "406523",
    "Rank": "Pte",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "S",
    "Enlistment": "Hawera",
    "Occupation": "Painter Decorator",
    "Address": "140 South Road, Hawera",
    "Next of Kin": "Mr E J Y Yearbury, 140 South Road, Hawera f",
    "Last rank Held": "Pte",
    "Date of Birth": "Wed Oct 12 1921 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sun Nov 09 2008 210000 GMT1300 New Zealand Daylight Time",
    "Age": "87",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Tue Dec 09 2008 21 00 00 GMT 1300 New Zealand Daylight Time",
    "Cemetery/Urupa and Where Known Plot Number": "Russell Cemetery Russell RSA Ash Berm Plot 25",
    "Husbands/Wives/Partners": "Paula Kahurangi Blomfield",
    "Place of birth": "Hawera",
    "Place of death": "Russell",
    "AL": "Y",
    "Notes": "Son of Edward Joseph and Elizabeth Malloch Yearbury, nee Lamb, of Hawera. Husband of Pauline Kahurangi Yearbury, nee Blomfield. Brother of Edward Yearbury. Place of birth: Hawera. Place of death: Russell. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yearbury",
    "Christian Name": "Leslie George",
    "Unit": "N Z A S C",
    "Name Variation": "Yearbury, Les",
    "Regtl. Number": "592181",
    "Rank": "Dvr",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "M",
    "Enlistment": "Warkworth",
    "Occupation": "Farmer",
    "Address": "Matakana, Warkworth",
    "Next of Kin": "Mrs Phyll M Yearbury, Yates Road, Mangere East w",
    "Last rank Held": "Dvr",
    "Date of Birth": "Wed Jul 28 1915 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Jul 25 1994 190000 GMT1200 New Zealand Standard Time",
    "Age": "78",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Wellsford Cemetery Wellsford RSA Section Block 1 Row A Plot 24 Seq 1 Burial",
    "Husbands/Wives/Partners": "Phyllis Mary Cullen",
    "Place of birth": "Mahurangi",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "Son of Frank Edward and Daisy Yearbury, nee Powdrill. Husband of Phyllis Mary Yearbury, nee Cullen, per the Marriage Index, of Mangere East. Place of birth: Mahurangi. Place of death: Whangarei. Ancestrylibrary.com.au. Photo of the grave plaque is on the Cenotaph database"
  },
  {
    "Surname": "Yelas",
    "Christian Name": "Stanley George",
    "Unit": "37 Bn",
    "Regtl. Number": "214917",
    "Rank": "Pte",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "S",
    "Enlistment": "Helensville",
    "Occupation": "Carpenter",
    "Address": "Stewart St, Helensville",
    "Next of Kin": "Mrs A M Yelas, Stewart St, Helensville m",
    "Date of Birth": "Sun Nov 14 1920 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Mon Mar 17 1997 200000 GMT1200 New Zealand Standard Time",
    "Age": "76",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Fri Mar 21 1997 20 00 00 GMT 1200 New Zealand Standard Time",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Newberrys Whg",
    "AL": "Y",
    "Notes": "Son of George and Ada M Yelas, of Helensville. Cremated at Maunu Cemetery, Whangarei; no other information. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yendell",
    "Christian Name": "Percival",
    "Unit": "18 Auck",
    "Name Variation": "Yendell, Percy",
    "Regtl. Number": "2713",
    "Rank": "Sgt",
    "Embarkation Dates": "M 40",
    "Marital Status": "M",
    "Enlistment": "Kaitaia",
    "Occupation": "Draper",
    "Address": "P O Box 5, Kaitaia",
    "Next of Kin": "Mrs Z de J Yendell, care of Mrs J Marbeck, Kenderdine Rd, Papatoetoe, Auckland w",
    "Date of Birth": "Mon May 18 1903 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Fri Mar 31 1978 200000 GMT1200 New Zealand Standard Time",
    "Age": "74",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Hamilton Park Cemetery Hamilton MAGN-06-040",
    "Funeral Director": "Pellows Funeral Services",
    "Husbands/Wives/Partners": "Zoe Joyce Mills",
    "Place of birth": "Nadrid North Molton England",
    "Place of death": "Hamilton",
    "AL": "Y",
    "Notes": "Brother of Walter Morley Yendell, who also served. Husband of Zoe Joyce Yendell, nee Mills per the Marriage Index, of Papatoetoe, Auckland. Death record in the name of Percy Yendell. Place of birth: Nadrid, North Molton, England. Place of death: Hamilton. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yendell",
    "Christian Name": "Walter Morley",
    "Unit": "Inf Bde",
    "Regtl. Number": "543445",
    "Rank": "T Sgt",
    "Embarkation Dates": "A 43-J 43",
    "Marital Status": "M",
    "Enlistment": "Kaitaia",
    "Occupation": "Grader driver",
    "Address": "Kaitaia",
    "Next of Kin": "Mrs E Yendell, C - E C Matthews, 110 R.D., Kaitaia w",
    "Last rank Held": "Sgt",
    "Date of Birth": "1905",
    "Date of Death": "Thu Apr 14 1966 200000 GMT1200 New Zealand Standard Time",
    "Age": "61",
    "Cemetery/Urupa and Where Known Plot Number": "Kaitaia Cemetery Kaitaia RSA Division Plot 78",
    "Funeral Director": "Geards Funeral Home",
    "Husbands/Wives/Partners": "Esther Matthews",
    "Place of birth": "South Molton Devon England",
    "Place of death": "Own residence Kaitaia",
    "AL": "Y",
    "Notes": "Brother of Percival Yendell, who also served. Son of Frederick Samuel and Mary Ann Chamings Yendell (Yendle?) nee Burnell. Husband of Esther Yendell, nee Matthews, of Kaitaia. Place of death: Own residence, Kaitaia. Place of birth: South Molton, Devon, England. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yerkovich",
    "Christian Name": "Steve",
    "Unit": "Inf Reinfs",
    "Regtl. Number": "619260",
    "Rank": "Pte",
    "Embarkation Dates": "A 44-D 44",
    "Marital Status": "S",
    "Enlistment": "Kaeo",
    "Occupation": "Farmer",
    "Address": "Matauri Bay",
    "Next of Kin": "Mrs M Yerkovich, Matauri Bay m",
    "Where Killed or Died": "Italy",
    "Cemetery Name": "Forli War",
    "Grave/Memorial Reference": "VI A 12",
    "Last rank Held": "Pte",
    "Date of Birth": "1920",
    "Date of Death": "Mon Dec 11 1944 190000 GMT1200 New Zealand Daylight Time",
    "Age": "24",
    "Burial/Cremation": "--",
    "AL": "Y",
    "Notes": "Son of Steve (Stjepan Matij) and (Tuia) (Tui) Mary (Mere) Yerkovich, (Yerkovic), nee Stewart, of Kaeo. Ancestrylibrary.com.au"
  },
  {
    "Surname": "York",
    "Christian Name": "Arnold Herbert Charles",
    "Unit": "N Z A S C",
    "Regtl. Number": "575322",
    "Rank": "Dvr",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "M",
    "Enlistment": "Palmerston North",
    "Occupation": "Omnibus driver",
    "Address": "C o C A York, Sanson",
    "Next of Kin": "Mrs L G York, 259 High St, Dannevirke w",
    "Last rank Held": "Dvr",
    "Date of Birth": "Mon Oct 24 1910 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat Nov 12 1977 210000 GMT1300 New Zealand Daylight Time",
    "Age": "67",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Maunu Cemetery Whangarei RSA Block Seventeen Plot 816",
    "Funeral Director": "Morris Morris Whg",
    "Husbands/Wives/Partners": "Lilian Gertrude Morris Ruth Frances Garlick",
    "Place of birth": "Auckland",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "Son of Charles Albert and Emma Christina York, nee Petersen. Husband of Lilian Gertrude York, nee Morris, per the Marriage Index, of Dannevirke. Husband of Ruth Frances York, nee Garlick. Place of birth: Auckland. Place of death: Whangarei. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yorke",
    "Christian Name": "Arthur Sydney",
    "Unit": "Inf Bde",
    "Name Variation": "Yorke, Pat",
    "Regtl. Number": "65119",
    "Rank": "Pte",
    "Embarkation Dates": "J 41-S 41",
    "Marital Status": "S",
    "Enlistment": "Kaeo",
    "Occupation": "Dairy farmer",
    "Address": "Kaeo",
    "Next of Kin": "Mr A Yorke, Horeke f",
    "Last rank Held": "Pte",
    "Date of Birth": "Thu Dec 23 1915 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Mon Apr 16 2007 190000 GMT1200 New Zealand Standard Time",
    "Age": "91",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Maunu Cemetery Maunu Whangarei Maunu Park Block Forty Four Plot 3805",
    "Husbands/Wives/Partners": "Eleanor Margaret Marg Sharland",
    "Place of birth": "Horeke",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "Son of Elbert (Albert Samuel) and Mate (Matahaeri) Matilda Yorke, nee Mapi. Husband of (Eleanor) Margaret (Marg) Yorke, nee Sharland. Father s initial is A in the NOK details. Place of birth: Horeke. Place of death: Whangarei. Arthur Yorke is as per birth index. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yorke",
    "Christian Name": "Ferguson",
    "Unit": "2 Div A S C Reinfs",
    "Name Variation": "Yorke, Fergusson",
    "Regtl. Number": "42881",
    "Rank": "Dvr",
    "Embarkation Dates": "A 41- J 41",
    "Marital Status": "S",
    "Enlistment": "Wellington",
    "Occupation": "Labourer",
    "Address": "20 Jessie St, Wellington",
    "Next of Kin": "Mrs B Yorke, Box 4, Paihia m",
    "Last rank Held": "Dvr",
    "Date of Birth": "Sat Dec 21 1912 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat Aug 19 1989 190000 GMT1200 New Zealand Standard Time",
    "Age": "76",
    "Burial/Cremation": "Cremation",
    "Cemetery/Urupa and Where Known Plot Number": "Paihia Cemetery Paihia RSA Ash Berms Block A Plot 7",
    "Funeral Director": "Unknown",
    "Place of birth": "NZ",
    "Place of death": "Paihia",
    "AL": "Y",
    "Notes": "Son of George Laurence (Lawrence) and (Peata Pariki) Beatrice Bertha (Bertha Beatrice Peata) Yorke, nee Smith-Murray, of Paihia. Place of birth: New Zealand. Place of death: Paihia. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yorke",
    "Christian Name": "Laurence",
    "Unit": "H Q 21 Auck",
    "Regtl. Number": "22531",
    "Rank": "Pte",
    "Embarkation Dates": "J 40",
    "Marital Status": "S",
    "Enlistment": "Auckland",
    "Occupation": "Labourer",
    "Address": "Paparimu",
    "Next of Kin": "Mr Jack Yorke, Paihia f",
    "Date of Birth": "See note",
    "Date of Death": "See note",
    "AL": "Y",
    "Notes": "Son of Jack Yorke, of Paihia. Lawrence Tucker Yorke in the 1987 Death Index - born 9 Jul 1918 ?? Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yorke",
    "Christian Name": "Mervyn Walter",
    "Unit": "Inf Reinfs",
    "Name Variation": "Yorke, Mervin Walter",
    "Regtl. Number": "619248",
    "Rank": "Pte",
    "Embarkation Dates": "J 45-D 45",
    "Marital Status": "S",
    "Enlistment": "Kawakawa",
    "Occupation": "Labourer",
    "Address": "Paihia",
    "Next of Kin": "Mrs E Yorke, P O Box 40, Paihia m",
    "Last rank Held": "Sgt",
    "Date of Birth": "Mon Nov 05 1923 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Thu Nov 30 1995 210000 GMT1300 New Zealand Daylight Time",
    "Age": "72",
    "Burial/Cremation": "Burial",
    "Ashes/Burial": "Mon Dec 04 1995 21 00 00 GMT 1300 New Zealand Daylight Time",
    "Cemetery/Urupa and Where Known Plot Number": "Paihia Cemetery RSA Block A Plot 28",
    "Funeral Director": "Squires Funeral Services",
    "Husbands/Wives/Partners": "Maureen Bernice Mary Becher",
    "Place of birth": "Haruru Falls",
    "Place of death": "Haruru Falls",
    "AL": "Y",
    "Notes": "Brother of Ronald Cliff and Roy Desmond Yorke, who also served. Son of Charles Edward and Era (Eva Pearl) Yorke, nee Clark, of Paihia. Husband of Maureen Bernice Mary Yorke, nee Becher. Place of birth and death: Haruru Falls. Mervin Walter Yorke is as per the Birth Index. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yorke",
    "Christian Name": "Ronald Cliff",
    "Unit": "4th Armd Bde",
    "Name Variation": "Yorke, Ronald Cliffe",
    "Regtl. Number": "80856",
    "Rank": "Tpr",
    "Embarkation Dates": "A 43-J 43",
    "Marital Status": "S",
    "Enlistment": "Kawakawa",
    "Occupation": "Shop assistant",
    "Address": "Paihia",
    "Next of Kin": "Mrs E Yorke, P O Box 40, Paihia m",
    "Last rank Held": "Pte",
    "Date of Birth": "Thu Dec 18 1919 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Tue Apr 27 2004 190000 GMT1200 New Zealand Standard Time",
    "Age": "84",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Sun Dec 19 2004 21 00 00 GMT 1300 New Zealand Daylight Time",
    "Cemetery/Urupa and Where Known Plot Number": "Paihia Cemetery RSA Ash Berms Block A Plot 20",
    "Funeral Director": "Newberrys Whg",
    "Husbands/Wives/Partners": "Kathleen Elsie Cummings",
    "AL": "Y",
    "Notes": "Brother of Mervyn Walter and Roy Desmond Yorke, who also served. Son of Charles Edward and Era (Eva Pearl) Yorke, nee Clark, of Paihia. Husband of Kathleen Elsie Yorke, nee Cummings. Date of death on internment record shows as 28 April 2004. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yorke",
    "Christian Name": "Roy Desmond",
    "Unit": "H Q Base",
    "Regtl. Number": "652605",
    "Rank": "Tpr",
    "Embarkation Dates": "Jan 46-Jun 48",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Labourer",
    "Address": "P O Box 40, Paihia",
    "Next of Kin": "Mrs E Yorke, P O Box 40, Paihia m",
    "Date of Birth": "1926",
    "Date of Death": "Fri Oct 21 2022 200000 GMT1300 New Zealand Daylight Time",
    "Age": "96",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Husbands/Wives/Partners": "Gloria Yorke",
    "AL": "Y",
    "Notes": "Brother of Mervyn Walter and Ronald Cliff Yorke, who also served. Son of Charles Edward and Era (Eva Pearl) Yorke, nee Clark, of Paihia. Husband of Gloria Yorke. Funeral service at St. Paul s Anglican Church, Paihia. Ancestrylibrary.com.auhttps://www.legacy.com/nz/obituaries/northernadvocate-nz/name/roy-yorke-obituary?pid 203057829"
  },
  {
    "Surname": "Yorke",
    "Christian Name": "Samuel Henry",
    "Unit": "Inf Reinfs",
    "Name Variation": "Yorke, Hamuera Henry Yorke, Sammy",
    "Regtl. Number": "29746",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Te Awamutu",
    "Occupation": "Farm hand",
    "Address": "Te Awamutu, Paihia",
    "Next of Kin": "Mr F Yorke, Paihia, Bay of Islands f",
    "Where Killed or Died": "Crete",
    "Cemetery Name": "Athens Memorial Phaleron War Athens Greece",
    "Grave/Memorial Reference": "Face 14",
    "Last rank Held": "Pte",
    "Date of Birth": "Sun Feb 23 1919 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sun May 25 1941 200000 GMT1200 New Zealand Standard Time",
    "Age": "22",
    "Burial/Cremation": "--",
    "Place of birth": "Paihia",
    "AL": "Y",
    "Notes": "Son of James Edward and Mary Wharenikau (Meri) ( Mary Joan) Kaire Yorke, nee Wikaira. Brother Edward Yorke, may possibly have served. Parents shown as Mr and Mrs E Yorke, of Paihia, on the CGC site. Father s initial is F in the NOK details. Place of birth: Paihia. Ancestrylibrary.com.au. https://paperspast.natlib.govt.nz/newspapers/AS19410619.2.105.2?query killed 20paihia"
  },
  {
    "Surname": "Yorke",
    "Christian Name": "Selwyn",
    "Unit": "Inf Reinfs",
    "Regtl. Number": "14618",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "M",
    "Enlistment": "Wellington",
    "Occupation": "Painter",
    "Address": "Care of Pukeora Sanitorium, Waipukurau",
    "Next of Kin": "Mrs J Yorke, 385 Riddell St, St. Heliers, Auckland wife",
    "Date of Birth": "Fri Dec 17 1920 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Fri May 15 1987 190000 GMT1200 New Zealand Standard Time",
    "Age": "66",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "N R",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Morris Morris Whg",
    "Husbands/Wives/Partners": "Margaret Evans J Yorke",
    "Place of birth": "Auckland",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "Son of Walter Thornton Abrahams and Gertrude Jane Yorke. Husband of Mrs J Yorke, of St. Heliers, Auckland. Husband of Margaret Yorke, nee Evans. Cremated at Maunu Cemetery, Whangarei; no other information. Place of birth: Auckland. Place of death: Whangarei. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Yorke",
    "Christian Name": "William Ernest",
    "Unit": "Inf Bde",
    "Name Variation": "Yorke, William Earnest",
    "Regtl. Number": "407879",
    "Rank": "Pte",
    "Embarkation Dates": "A 43-J 43",
    "Marital Status": "S",
    "Enlistment": "Hamilton",
    "Occupation": "Farmer",
    "Address": "Paihia",
    "Next of Kin": "Mr W G J Yorke, P O Paihia f",
    "Date of Birth": "Sat Oct 21 1916 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Mon Oct 20 1997 200000 GMT1300 New Zealand Daylight Time",
    "Age": "80",
    "Place of birth": "NZ",
    "Place of death": "Haruru",
    "AL": "Y",
    "Notes": "Son of William George John and Rehutai (Janie) Te Rangi (Jane) Yorke, nee Cross?, of Paihia. William Earnest Yorke is as per the Birth Index. Geni.com. Place of birth: New Zealand. Place of death: Haruru. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Youatt",
    "Christian Name": "Quita O Cinidi",
    "Unit": "N Z A N S",
    "Name Variation": "See Cordner, Quita O'Cinidi",
    "Regtl. Number": "812234",
    "Rank": "Sister",
    "Embarkation Dates": "A 43-J 43",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Nurse",
    "Rolls": "NZANS",
    "Address": "Emergency Hosp., Whangarei",
    "Next of Kin": "Mrs E M Cordner, 73 Rossall St, Ch'ch. m",
    "Date of Birth": "Wed Aug 27 1913 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sat Jan 01 2011 210000 GMT1300 New Zealand Daylight Time",
    "Age": "97",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Husbands/Wives/Partners": "Brian Dinsdale Youatt",
    "Place of birth": "Christchurch",
    "Place of death": "Norwich Norfolk England",
    "AL": "Y",
    "Notes": "Daughter of Edward James O'Cinidi and Ethel Mildred Cordner, nee Rhodes, of Christchurch. Wife of Brian Dinsdale Youatt. Place of birth: Christchurch. Place of death: Norwich, Norfolk, England. Ancestrylibrary.com.au https://www.theguardian.com/theguardian/2011/feb/03/quita-youatt-obituary .. http://www.amemorytree.co.nz/personnotices.php?personid 119669 ."
  },
  {
    "Surname": "Youl",
    "Christian Name": "Victor Albert William",
    "Unit": "N Z A",
    "Name Variation": "Youl, Vic",
    "Regtl. Number": "166667",
    "Rank": "Gnr",
    "Embarkation Dates": "J 43- D 43",
    "Marital Status": "S",
    "Enlistment": "Wellington",
    "Occupation": "Draughtsman",
    "Address": "504 Evans Bay Road, Wellington",
    "Next of Kin": "Mr A J S Youl, 504 Evans Bay Road, Wellington f",
    "Date of Birth": "Fri Nov 04 1921 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Thu Oct 13 2011 200000 GMT1300 New Zealand Daylight Time",
    "Age": "89",
    "Burial/Cremation": "Cremation",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Husbands/Wives/Partners": "Rosalind Joy Knight",
    "Place of birth": "Wellington",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "Son of Albert Joseph Samuel and Clara Eveline Youl, nee Baker, of Wellington. Husband of (Rosalind) Joy Youl, nee Knight. Ancestry.co.uk. Place of death: Whangarei. Place of birth: Wellington. Place of cremation unknown. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Young",
    "Christian Name": "Austin John",
    "Unit": "Inf Reinfs",
    "Regtl. Number": "14555",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Auckland",
    "Occupation": "Labourer",
    "Address": "43 Hayden St, Auckland",
    "Next of Kin": "Mrs C E Young, Kirikiri Rd, Whangarei mother",
    "Where Killed or Died": "Tunisia",
    "Cemetery Name": "Sfax War Tunisia",
    "Grave/Memorial Reference": "XI E 22",
    "Last rank Held": "Pte",
    "Date of Birth": "Sun Jul 11 1920 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Fri Mar 26 1943 190000 GMT1200 New Zealand Daylight Time",
    "Age": "22",
    "Burial/Cremation": "--",
    "AL": "Y",
    "Notes": "Son of Charlie and Clara Elizabeth Young, of Whangarei. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Young",
    "Christian Name": "Desmond",
    "Unit": "Inf Reinfs",
    "Regtl. Number": "26166",
    "Rank": "S Sgt",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "M",
    "Enlistment": "Kaitaia",
    "Occupation": "Shepherd",
    "POW": "Y",
    "Place of capture": "Egypt",
    "Address": "C - Mr A Yarborough, Private Bag, Kohukohu",
    "Next of Kin": "Mrs Veda A Young, C - R E Carman, Broadwood w",
    "Last rank Held": "Sgt",
    "Date of Birth": "Thu Jun 15 1916 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Nov 02 1959 200000 GMT1200 New Zealand Daylight Time",
    "Age": "43",
    "Burial/Cremation": "Cremation",
    "Cemetery/Urupa and Where Known Plot Number": "Waikumete Cemetery Glen Eden Auckland New Zealand Soldiers Ash Burial K Row 2a Plot 3",
    "Husbands/Wives/Partners": "Veda Annie Robertson",
    "Place of birth": "Potarlington Ireland",
    "Place of death": "Auckland Hospital Auckland",
    "AL": "Y",
    "Notes": "POW. Son of William Digby and Jane Cooke Young. Husband of Veda Annie Young, nee Robertson, of Broadwood. Place of death: Auckland Hospital, Auckland. Bio on Cenotaph database. Details of POW Camps are on the Cenotaph database. Place of birth: Portarlington, Ireland. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Young",
    "Christian Name": "Ernest Patrick",
    "Unit": "Inf Bde",
    "Regtl. Number": "67113",
    "Rank": "Pte",
    "Embarkation Dates": "J 41-S 41",
    "Marital Status": "S",
    "Enlistment": "Kawakawa",
    "Occupation": "Farmer",
    "Address": "R.D., Kaikohe",
    "Next of Kin": "Mrs B F Haines, Motukaraka m",
    "Where Killed or Died": "West Des",
    "Cemetery Name": "El Alamein War Egypt",
    "Grave/Memorial Reference": "XXX C 25",
    "Last rank Held": "Pte",
    "Date of Birth": "Mon Jan 20 1908 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Fri Jun 26 1942 190000 GMT1200 New Zealand Standard Time",
    "Age": "34",
    "Burial/Cremation": "--",
    "AL": "Y",
    "Notes": "Son of Arthur Henry and Bridget Florence Young, nee O'Dea, (later Haines?) of Punakitere. On the 21st Battalion Roll of Honour, Auckland Museum. Place of birth: Rawene. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Young",
    "Christian Name": "Iris Mary",
    "Unit": "N Z A N S",
    "Name Variation": "Turnbull, Iris Mary",
    "Regtl. Number": "48331",
    "Rank": "Sister",
    "Embarkation Dates": "O 41- D 41",
    "Marital Status": "S",
    "Enlistment": "Auckland",
    "Occupation": "Registered Nurse",
    "Rolls": "NZANS",
    "Address": "2 Horonui St, Whangarei",
    "Next of Kin": "Mrs S J Young, 2 Horonui St, Whangarei m",
    "Date of Birth": "Wed May 06 1914 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "15/01/2017",
    "Age": "102",
    "Husbands/Wives/Partners": "F Allen",
    "Place of birth": "Auckland",
    "AL": "Y",
    "Notes": "Daughter of Angus Theodore and Sarah Janet Maud Young, nee Driffill, of Whangarei. Wife of F Allen. Place of birth: Auckland. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Young",
    "Christian Name": "Miles Archibald",
    "Unit": "H Q 24 Auck",
    "Regtl. Number": "23082",
    "Rank": "Lt",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "M",
    "Enlistment": "Auckland",
    "Occupation": "Mechanical engineer",
    "POW": "Y",
    "Place of capture": "Unknown",
    "Address": "8 O'Neill's Ave, Takapuna",
    "Next of Kin": "Mrs M M Young, 8 O'Neill's Ave, Takapuna wife",
    "Date of Birth": "Thu Jul 28 1904 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sun Mar 14 1976 200000 GMT1200 New Zealand Standard Time",
    "Age": "71",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Kaurihohore Cemetery Kauri Whangarei BERM Row B Plot 18",
    "Funeral Director": "Not stated",
    "Husbands/Wives/Partners": "Jessie Margaret Young May Marjorie Margery Ross Marjory Isabella Frances Margerita Cattell",
    "Place of birth": "St Leonard St Mary Magdalen Sussex England",
    "Place of death": "NZ",
    "AL": "Y",
    "Notes": "POW. Son of Archibald Edward and Cicely Young, nee Ashton. Husband of Jessie Margaret Young. Husband of May Marjorie (Marjery) Young, nee Ross. Husband of Marjory Isabella Frances (Margerita) Young, nee Cattell. Place of birth: St. Leonard, (St. Mary Magdalen) Sussex, England. Place of death: New Zealand. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Young",
    "Christian Name": "Neil Maxwell",
    "Unit": "H Q Inf Bde",
    "Regtl. Number": "270707",
    "Rank": "Pte",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Carpenter",
    "Address": "Cove, Waipu",
    "Next of Kin": "Mrs S V Young, Cove, Waipu m",
    "Last rank Held": "Pte",
    "Date of Birth": "Sun Jul 10 1921 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sun Sep 08 2002 190000 GMT1200 New Zealand Standard Time",
    "Age": "81",
    "Cemetery/Urupa and Where Known Plot Number": "Waipu Cemetery Waipu",
    "Husbands/Wives/Partners": "Ava Muriel Mary Smith",
    "Place of birth": "Morrinsville",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "Son of John Maxwell and Sybil Vivian Young, nee Campbell, of Waipu. Husband of Ava Muriel Mary Young, nee Smith. Parents per the Birth Index are Dan Neil and Emily Sarah Young. Plot no. is unknown. Place of birth: Morrinsville. Place of death: Whangarei. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Young",
    "Christian Name": "Neil Maxwell",
    "Unit": "Inf Reinfs",
    "Regtl. Number": "270707",
    "Rank": "Pte",
    "Embarkation Dates": "J 45-D 45",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Carpenter",
    "Address": "Cove, Waipu",
    "Next of Kin": "Mrs S V Young, 11 Akiraho St, Mt. Eden m",
    "Last rank Held": "Pte",
    "Date of Birth": "Sun Jul 10 1921 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sun Sep 08 2002 190000 GMT1200 New Zealand Standard Time",
    "Age": "81",
    "Cemetery/Urupa and Where Known Plot Number": "Waipu Cemetery Waipu",
    "Husbands/Wives/Partners": "Ava Muriel Mary Smith",
    "Place of birth": "Morrinsville",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "Son of John Maxwell and Sybil Vivian Young, nee Campbell, of Waipu. Husband of Ava Muriel Mary Young, nee Smith. Parents per the Birth Index are Dan Neil and Emily Sarah Young. Plot no. is unknown. Place of birth: Morrinsville. Place of death: Whangarei. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Young",
    "Christian Name": "Robert Carmichael",
    "Unit": "23 Canto",
    "Regtl. Number": "10681",
    "Rank": "Pte",
    "Embarkation Dates": "J 40",
    "Marital Status": "S",
    "Enlistment": "Blenheim",
    "Occupation": "Farmer",
    "Address": "Rai Valley, Marlborough",
    "Next of Kin": "Mrs E H Young, Rai Valley, Marlborough m",
    "Date of Birth": "Sat Sep 06 1902 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sun Nov 07 1971 200000 GMT1200 New Zealand Standard Time",
    "Age": "69",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Maunu Cemetery Whangarei Forest Lawn Block Twenty One Plot 1709",
    "Funeral Director": "Morris Morris Whg",
    "Husbands/Wives/Partners": "Lilian Olive Young",
    "Place of birth": "Havelock",
    "Place of death": "Waikato",
    "AL": "Y",
    "Notes": "MM. Son of David and Elizabeth Lilian Houghton Young, nee Cawte, of Rai Valley. Husband of Lilian Olive Young. Per Cenotaph record the citation is in the name of Robert Charles Young? Place of birth; Havelock. Place of death: Waikato. Bio on Cenotaph database. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Young",
    "Christian Name": "Rupert",
    "Unit": "18 Auck",
    "Regtl. Number": "3158",
    "Rank": "Pte",
    "Embarkation Dates": "M 40",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Barman",
    "Address": "C - Whangarei Post Office",
    "Next of Kin": "Mrs B Young, Sydbury, England mother",
    "Date of Birth": "Wed Oct 23 1907 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sun Nov 28 1993 210000 GMT1300 New Zealand Daylight Time",
    "Age": "86",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Wed Dec 01 1993 21 00 00 GMT 1300 New Zealand Daylight Time",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Newberrys Whg",
    "AL": "Y",
    "Notes": "Son of Mrs B Young, of Sydbury, England. Possibly born in Sidmouth, Devon, England in 1907 parents Julian Elton and Blanche Emily Young, nee McDermott. Cremated at Maunu Cemetery & Crematorium, Whangarei; no other information. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Young",
    "Christian Name": "Stanley Lake",
    "Unit": "Inf Bde",
    "Regtl. Number": "459655",
    "Rank": "T Cpl",
    "Embarkation Dates": "J 44-M 44",
    "Marital Status": "S",
    "Enlistment": "Kawakawa",
    "Occupation": "Farm hand",
    "Address": "Kaikohe",
    "Next of Kin": "Mrs C S Young, Kaikohe m",
    "Date of Birth": "Tue Mar 27 1923 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Fri Jul 05 2013 190000 GMT1200 New Zealand Standard Time",
    "Age": "90",
    "Husbands/Wives/Partners": "Isobel Wilson Hayton",
    "Place of birth": "Rawene",
    "Place of death": "Te Omanga Hospice Lower Hutt",
    "AL": "Y",
    "Notes": "OBE. Son of Hubert Frank and Charlotte Susan Young, nee White, of Kaikohe. Husband of Isobel Wilson Young, nee Hayton. Place of birth: Rawene. Place of death: Te Omanga Hospice, Lower Hutt. Funeral service held at Trentham Military Camp, Officers Mess. Familysearch.org. Ancestrylibrary.com.au. Legacy.com. https://www.heavenaddress.com/Stanley-Lake-Young/444731/service_details. https://www.armymuseum.co.nz/kiwis-at-war/voices-from-the-past/rugby-hero-remembered/"
  },
  {
    "Surname": "Young",
    "Christian Name": "Stephen Leopold",
    "Unit": "7 Fd Coy",
    "Regtl. Number": "21893",
    "Rank": "Spr",
    "Embarkation Dates": "J 40",
    "Marital Status": "S",
    "Enlistment": "Rotorua",
    "Occupation": "Carpenter",
    "Address": "58 Malfroy Rd, Rotorua",
    "Next of Kin": "Mr Y A Young, Dargaville f",
    "Last rank Held": "Sgt",
    "Date of Birth": "Thu Nov 18 1915 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Tue Aug 25 1981 190000 GMT1200 New Zealand Standard Time",
    "Age": "65",
    "Cemetery/Urupa and Where Known Plot Number": "Papakura Cemetery Papakura Auckland Lot PRSAA-X-016",
    "Husbands/Wives/Partners": "Rose Watts",
    "Place of birth": "Auckland",
    "Place of death": "Manurewa Auckland",
    "AL": "Y",
    "Notes": "Son of James Andrew and Constance Gabrielle Young, nee Sarich, of Dargaville. Husband of Rose Young, nee Watts. Father s initials are Y A in the NOK details. Place of birth: Auckland. Place of death: Manurewa, Auckland. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Young",
    "Christian Name": "Thomas Alexander",
    "Unit": "N Z M C",
    "Regtl. Number": "82614",
    "Rank": "Pte",
    "Embarkation Dates": "A 43-J 43",
    "Marital Status": "S",
    "Enlistment": "Helensville",
    "Occupation": "Farm hand",
    "Address": "C - Vermon Stud Farm, Wharepapa",
    "Next of Kin": "Mrs A M Young, Houto, R.D., Whangarei m",
    "Last rank Held": "Pte",
    "Date of Birth": "Thu May 27 1920 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Tue Apr 01 1997 200000 GMT1200 New Zealand Standard Time",
    "Age": "76",
    "Burial/Cremation": "Burial",
    "Ashes/Burial": "Thu Apr 03 1997 20 00 00 GMT 1200 New Zealand Standard Time",
    "Cemetery/Urupa and Where Known Plot Number": "Kerikeri Wiroa Cemetery RSA Block X Plot 27",
    "Funeral Director": "Scott Funeral Services",
    "Place of birth": "Kawakawa",
    "Place of death": "Haruru Falls",
    "AL": "Y",
    "Notes": "Brother of William Wallis Young, who also served and Roderick Alan Young, who served in the R.N.Z.A.F. Son of Alexander Matheson and Annie Mary Agnes Young, nee Jennings, of Houto. Place of death: Haruru Falls. Place of birth: Kawakawa. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Young",
    "Christian Name": "Walter",
    "Unit": "17 Ry Op Coy",
    "Name Variation": "Young, Wally",
    "Regtl. Number": "27666",
    "Rank": "Spr",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Fireman",
    "Address": "Post Office, Hikurangi",
    "Next of Kin": "Mrs L M Young, Post Office, Hikurangi mother",
    "Last rank Held": "Pte",
    "Date of Birth": "Tue Aug 06 1918 183000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sun Apr 11 1999 190000 GMT1200 New Zealand Standard Time",
    "Age": "80",
    "Cemetery/Urupa and Where Known Plot Number": "Kaurihohore Cemetery Whangarei",
    "Husbands/Wives/Partners": "Elizabeth Clare Connolly",
    "Place of birth": "Bishop Auckland Durham England",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "Son of Herbert and Lilian May Young, of Hikurangi, per FAG. Husband of Elizabeth Clare Young, nee Connolly. Place of birth: Bishop Auckland, Durham, England. Place of death: Whangarei. Date of death on Cenotaph record is incorrect. Plot no. is not known. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Young",
    "Christian Name": "Walter Frederick",
    "Unit": "N Z E",
    "Regtl. Number": "453599",
    "Rank": "Pte",
    "Embarkation Dates": "J 43- D 43",
    "Marital Status": "S",
    "Enlistment": "Silverdale",
    "Occupation": "Farm Hand",
    "Address": "Browns Bay, Auckland",
    "Next of Kin": "Mrs B M L Young, C - M E Fletcher, 841 Mt Eden Road, Auckland w",
    "Last rank Held": "L Cpl",
    "Date of Birth": "Mon Apr 10 1922 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Nov 22 1999 210000 GMT1300 New Zealand Daylight Time",
    "Age": "77",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Maunu Cemetery Maunu Whangarei Maunu Park Block Twenty Seven Plot 3034",
    "Funeral Director": "Morris Morris Whg",
    "Husbands/Wives/Partners": "Barene Mary Lovene Fletcher Pat Young",
    "Place of birth": "NZS",
    "Place of death": "NZ",
    "AL": "Y",
    "Notes": "Son of Frederick John and Dorothy Irene Young, nee Coleman. Husband of Pat Young. Husband of Barene Mary Lovene Young, nee Fletcher. Place of birth and death: New Zealand. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Young",
    "Christian Name": "William Allen",
    "Unit": "4th Armd Bde",
    "Name Variation": "Young, William Allan",
    "Regtl. Number": "48242",
    "Rank": "Cpl",
    "Embarkation Dates": "A 43-J 43",
    "Marital Status": "M",
    "Enlistment": "Auckland",
    "Occupation": "Carpenter",
    "Address": "3 McCall St, Newmarket, Auck.",
    "Next of Kin": "Mrs O L Young, Motatau w",
    "Date of Birth": "Fri Oct 06 1916 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Wed Aug 11 1993 190000 GMT1200 New Zealand Standard Time",
    "Age": "76",
    "Husbands/Wives/Partners": "Olive Lillian Hart",
    "Place of birth": "Invercargill",
    "Place of death": "NZ",
    "AL": "Y",
    "Notes": "Brother of Ronald James Young, who also served. Son of Allan James and Emily Jane Young, nee Smith. Husband of Olive Lillian Young, nee Hart, per the Marriage Index, of Motatau. William Allan Young is as per the Birth Index. Place of birth: Invercargill. Place of death: New Zealand. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Young",
    "Christian Name": "William Wallis",
    "Unit": "2 Div Sigs",
    "Regtl. Number": "72541",
    "Rank": "Sgmn",
    "Embarkation Dates": "A 42-J 42",
    "Marital Status": "S",
    "Enlistment": "Auckland",
    "Occupation": "Canistermaker",
    "Address": "34 Tawa Rd, Onehunga",
    "Next of Kin": "Mrs A M A Young, Hauto Rd, Whangarei m",
    "Date of Birth": "Thu May 27 1920 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Fri Jul 11 2008 190000 GMT1200 New Zealand Standard Time",
    "Age": "88",
    "AL": "Y",
    "Notes": "Brother of Thomas Alexander Young, who also served and Roderick Alan Young, who served in the R.N.Z.A.F. . Son of Alexander Matheson and Ammie Mary Agnes Young, nee Jennings, of Whangarei. Ancestrylibrary.com.au"
  }
];