const veteransDataV = [
  {
    "Surname": "Vaile",
    "Christian Name": "Roy Harold",
    "Unit": "N Z M C",
    "Regtl. Number": "452382",
    "Rank": "Pte",
    "Embarkation Dates": "A 44-D 44",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Dairy factory hand",
    "Address": "Waipu Cove, Whangarei",
    "Next of Kin": "Mrs W I Vaile, Waipu Cove m",
    "Last rank Held": "Sgt",
    "Date of Birth": "Sat Nov 25 1922 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Tue Jan 08 1985 210000 GMT1300 New Zealand Daylight Time",
    "Age": "62",
    "Cemetery/Urupa and Where Known Plot Number": "Waipu Cemetery Waipu",
    "Husbands/Wives/Partners": "Constance Heather Jackman",
    "Place of birth": "Whangarei",
    "Place of death": "Waipu",
    "AL": "Y",
    "Notes": "Son of Harold Lartius (Larty) Vaile, who served here in NZ and Winifred Judith Vaile, nee Byles, of Waipu Cove. Husband of Constance Heather Vaile, nee Jackman. Plot no. is unknown. Mother s initial is W I in the NOK details. Place of birth: Whangarei. Place of death: Waipu. Geni.com. Myheritage.com. Familysearchfamilytree. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Valder",
    "Christian Name": "Arthur Noel",
    "Unit": "Inf Reinfs",
    "Name Variation": "Valder, Noel Arthur",
    "Regtl. Number": "169325",
    "Rank": "Pte",
    "Embarkation Dates": "J 45-D 45",
    "Marital Status": "M",
    "Enlistment": "Tauranga",
    "Occupation": "Dairy farmer",
    "Address": "Te Matai Rd, Te Puke",
    "Next of Kin": "Mrs G O Valder, C. - Mrs L Sloane, Church Rd, Kaitaia w",
    "Date of Birth": "Mon Dec 26 1921 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sun Apr 04 2010 190000 GMT1200 New Zealand Standard Time",
    "Age": "88",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Mon Apr 12 2010 19 00 00 GMT 1200 New Zealand Standard Time",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Jones Company Funeral Services",
    "Husbands/Wives/Partners": "Gwendoline Olive Valder",
    "Place of birth": "Dargaville",
    "AL": "Y",
    "Notes": "Brother of Keith Erskine Valder, who also served. Son of Alfred Robert and Mary Ellen Valder, nee Erskine. Husband of Gwendoline Olive Valder, of Kaitaia. Cremated at Pyes Pa Cemetery & Crematorium, Tauranga; no other information. Place of birth: Dargaville. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Valder",
    "Christian Name": "Keith Erskine",
    "Unit": "N Z E",
    "Regtl. Number": "532524",
    "Rank": "Cpl",
    "Embarkation Dates": "J 43- D 43",
    "Marital Status": "M",
    "Enlistment": "Kawakawa",
    "Occupation": "Turner and fitter",
    "Address": "Broadway, Kaikohe",
    "Next of Kin": "Mrs N M Valder, P O Box 45, Kaikohe w",
    "Date of Birth": "Wed Aug 11 1909 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sat Feb 23 1985 210000 GMT1300 New Zealand Daylight Time",
    "Age": "75",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Kaikohe Cemetery Public Lawn Block C Plot 71",
    "Funeral Director": "Unknown",
    "Husbands/Wives/Partners": "Maria Netta Netta Maria Hastie",
    "Place of birth": "Gisborne",
    "Place of death": "Kaikohe",
    "AL": "Y",
    "Notes": "Brother of Arthur Noel Valder, who also served. Son of Alfred Robert and Mary Ellen Valder, nee Erskine. Husband of Maria Netta (Netta Maria) Valder, nee Hastie, of Kaikohe. Place of birth: Gisborne. Place of death: Kaikohe. Wife s initial is N M in the NOK details. Wikitree.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Valentine",
    "Christian Name": "Trevor Adolphus",
    "Unit": "2 Div N Z A",
    "Regtl. Number": "46145",
    "Rank": "Gnr",
    "Embarkation Dates": "J 44-M 44",
    "Marital Status": "S",
    "Enlistment": "Auckland",
    "Occupation": "Cable jointer",
    "Address": "29 Abbotsford Tce, Devonport, Auckland",
    "Next of Kin": "Mrs T Vance, 29 Abbotsford Tce, Devonport, Auckland s",
    "Last rank Held": "A Bdr",
    "Date of Birth": "Sun Jul 11 1920 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Fri Jul 11 1958 190000 GMT1200 New Zealand Standard Time",
    "Age": "38",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Maunu Cemetery Whangarei RSA Block Ten Plot 248",
    "Funeral Director": "Newberrys Whg",
    "Place of birth": "Auckland",
    "Place of death": "Kaitaia",
    "AL": "Y",
    "Notes": "Son of Adolphus Henrici and Gertrude Philomena (Philomene) Valentine nee Clark(e). Brother of Mrs T Vance, of Devonport, Auckland. Place of birth: Auckland. Place of death: Kaitaia. The grandparents names are on the Birth Index showing as parents. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Van Dyke",
    "Christian Name": "Vincent Alan",
    "Unit": "3 Bn",
    "Regtl. Number": "812891",
    "Rank": "Pte",
    "Embarkation Dates": "Jan 46-Jun 48",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Driver",
    "Address": "5 Cafler's Ave, Whangarei",
    "Next of Kin": "Mrs A Van Dyke, 43 Ranfurly Rd, Onehunga m",
    "Date of Birth": "See note",
    "Date of Death": "See note",
    "AL": "Y",
    "Notes": "Son of Mrs A Van Dyke, of Onehunga, Auckland. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Van Opdorp",
    "Christian Name": "Alma Mary",
    "Unit": "N Z A N S",
    "Name Variation": "See under Chapman, Alma Chapman, Alma Mary",
    "Regtl. Number": "802834",
    "Rank": "Sister",
    "Embarkation Dates": "Jan 43- Mar 43",
    "Marital Status": "S",
    "Enlistment": "Dargaville",
    "Occupation": "Nurse",
    "Rolls": "NZANS",
    "Address": "Public Hospital, Te Kopuru",
    "Next of Kin": "Mr S Chapman, P O Box 50, Clyde f",
    "Last rank Held": "Sister",
    "Date of Birth": "25/03/1912",
    "Date of Death": "Thu Aug 25 1966 190000 GMT1200 New Zealand Standard Time",
    "Age": "54",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Taita Lawn Cemetery Naenae Lower Hutt Block 11 Row A Plot 18",
    "Husbands/Wives/Partners": "Albert Christian Van Opdorp",
    "Place of birth": "Grey",
    "AL": "Y",
    "Notes": "Wife of Albert Christian Van Opdorp, who served in the Merchant Navy. Daughter of Samuel Patrick and Martha Chapman, nee Hudd, of Clyde. Place of birth: Grey. Alina Mary Chapman is as per the Birth Index. FS. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Vaudrey",
    "Christian Name": "Alan Douglas",
    "Unit": "17 Ry Op Coy",
    "Regtl. Number": "27665",
    "Rank": "Spr",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "M",
    "Enlistment": "Whangarei",
    "Occupation": "Fireman",
    "Address": "3 Second Ave, Whangarei",
    "Next of Kin": "Mrs E E Vaudrey, 12 Duke St, Dominion Rd, Auckland S.2. wife",
    "Last rank Held": "Spr",
    "Date of Birth": "Wed Apr 04 1917 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Oct 15 2001 200000 GMT1300 New Zealand Daylight Time",
    "Age": "84",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Wed Apr 03 2002 20 00 00 GMT 1200 New Zealand Standard Time",
    "Cemetery/Urupa and Where Known Plot Number": "Totara Memorial Park Thames 2RSAA-PLOT-0084",
    "Funeral Director": "Twentymans Funeral Services",
    "Husbands/Wives/Partners": "Florence May Vaudrey Edith Ethel Vaudrey",
    "Place of birth": "Loughborough Leicestershire England",
    "Place of death": "Ngatea",
    "AL": "Y",
    "Notes": "Son of Herbert and Grace Spencer Vaudrey, nee Newton. Husband of Florence May Vaudrey. Husband of Edith Ethel Vaudrey. Resided with his wife in Whangarei. Born in Loughborough, Leicestershire, England. Place of death: Ngatea. Cremated at Hamilton Park Cemetery & Crematorium, Hamilton. Last address: 921 Tararu Rd, Thames. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Vause",
    "Christian Name": "Clifford",
    "Unit": "Inf Reinfs",
    "Regtl. Number": "63343",
    "Rank": "Pte",
    "Embarkation Dates": "A 41- J 41",
    "Marital Status": "S",
    "Enlistment": "Dargaville",
    "Occupation": "Grocer s assistant",
    "POW": "Y",
    "Place of capture": "West Des",
    "Address": "Haimona Street, Dargaville",
    "Next of Kin": "Mrs M Vause, Dargaville m",
    "Last rank Held": "Pte",
    "Date of Birth": "Tue Jun 12 1917 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Aug 09 2004 190000 GMT1200 New Zealand Standard Time",
    "Age": "87",
    "Cemetery/Urupa and Where Known Plot Number": "Mt Wesley Cemetery Dargaville",
    "Husbands/Wives/Partners": "Marjorie Rae Gould",
    "Place of birth": "Dargaville",
    "Place of death": "Dargaville",
    "AL": "Y",
    "Notes": "POW. Son of Cecil Robert and Jessie Maud Vause, nee Rowland, of Dargaville. Husband of Marjorie Rae Vause, nee Gould. Mother s initial is M in the NOK details. Place of birth: Dargaville. Place of death: Dargaville. Also served previously in territorials. Wounded. Bio on Cenotaph database. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Vazey",
    "Christian Name": "Mervyn Lloyd",
    "Unit": "Armd Bde",
    "Regtl. Number": "66247",
    "Rank": "Tpr",
    "Embarkation Dates": "J 44-M 44",
    "Marital Status": "S",
    "Enlistment": "Kaitaia",
    "Occupation": "Shop-assistant",
    "Address": "Awanui",
    "Next of Kin": "Mrs R A Vazey, P O Box 25, Awanui m",
    "Last rank Held": "Sgt",
    "Date of Birth": "Wed Jul 14 1920 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sun Sep 11 1977 190000 GMT1200 New Zealand Standard Time",
    "Age": "57",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Kaitaia Cemetery Kaitaia RSA Division Plot 186",
    "Funeral Director": "Geards Funeral Home",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "Brother of Ronald Adam Vazey, who also served. Son of Adam Okura and Rose May Vazey, nee Hutley, of Awanui. Mother s initials are R A on the Birth Index. Place of death: Auckland. Date of death and age on cemetery record is incorrect. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Vazey",
    "Christian Name": "Ronald Adam",
    "Unit": "4th Armd Bde",
    "Name Variation": "Vazey, Ron",
    "Regtl. Number": "80768",
    "Rank": "Cpl",
    "Embarkation Dates": "A 43-J 43",
    "Marital Status": "M",
    "Enlistment": "Kaitaia",
    "Occupation": "Driver",
    "Address": "Awanui",
    "Next of Kin": "Mrs E J Vazey, C - H Christensen, 111 R.D., Kaitaia w",
    "Last rank Held": "2 Lt",
    "Date of Birth": "Mon Oct 15 1917 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Mon Mar 19 1973 200000 GMT1200 New Zealand Standard Time",
    "Age": "55",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Kaitaia Cemetery Kaitaia RSA Division Plot 137",
    "Funeral Director": "Geards Funeral Home",
    "Husbands/Wives/Partners": "Edna Joyce Christensen",
    "Place of birth": "Awanui",
    "Place of death": "Whangarei Hospital Whangarei",
    "AL": "Y",
    "Notes": "MC. Brother of Mervyn Lloyd Vazey, who also served. Son of Adam Okura and Rose May Vazey, nee Hutley. Husband of Edna Joyce Vazey, nee Christensen, of Kaitaia, per FAG. Bio on Cenotaph database. Place of birth: Awanui. Place of death: Whangarei Hospital, Whangarei. Age is shown as 54 on the cemetery record. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Venables",
    "Christian Name": "Austell Malcolm",
    "Unit": "2 Div A S C Reinfs",
    "Name Variation": "Venables, Anstell Malcolm Venables, Tom",
    "Regtl. Number": "28652",
    "Rank": "Dvr",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Whakatane",
    "Occupation": "Baker and chef",
    "Address": "A W Logan, Kaitaia",
    "Next of Kin": "Mr Vernon Venables, Hunterville f",
    "Date of Birth": "Thu Dec 19 1918 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat Jul 22 1989 190000 GMT1200 New Zealand Standard Time",
    "Age": "70",
    "Cemetery/Urupa and Where Known Plot Number": "Western Hills Cemetery Napier",
    "Funeral Director": "Dunstall s Funeral Services Ltd",
    "Husbands/Wives/Partners": "Marjorie Jean Miller Mima Eileen Watson",
    "Place of birth": "Napier",
    "Place of death": "Napier",
    "AL": "Y",
    "Notes": "Son of Vernon and Miriam Athol(e) Rachel Venables, nee Kemp, of Hunterville. Husband of Marjorie Jean Venables, nee Miller and Mima Eileen Venables, nee Watson. Place of birth and death: Napier. Photo of gravestone is on the cemetery index. Geni.com. Ancestrylibrary.com.au. https://www.kempfamilyhistory.com/getperson.php?personID I39164&tree adkemp. Place of death: Napier. Last address: 107 King St, Taradale, Napier."
  },
  {
    "Surname": "Venables",
    "Christian Name": "Dorothy Rhoda",
    "Unit": "N Z A N S",
    "Regtl. Number": "810720",
    "Rank": "Sister",
    "Embarkation Dates": "J 45-D 45",
    "Marital Status": "S",
    "Enlistment": "Auckland",
    "Occupation": "Nurse",
    "Rolls": "NZANS",
    "Address": "113A Great South Rd, Auck.",
    "Next of Kin": "Mrs D H Venables, Bare Lands , Tomarata, R.D., Wellsford m",
    "Date of Birth": "Thu May 31 1917 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Fri Nov 21 2003 210000 GMT1300 New Zealand Daylight Time",
    "Age": "86",
    "AL": "Y",
    "Notes": "Daughter of Mrs D H Venables, of Tomarata. Mother believed to be Dorothy Hope Venables. Ancestrylibrary.com.au. Some information possibly in this pdf - http://www.methodist.org.nz/files/docs/wesley 20historical/out 20of 20the 20silence.pdf"
  },
  {
    "Surname": "Vennell",
    "Christian Name": "Arthur Henry",
    "Unit": "6 Fd Coy",
    "Regtl. Number": "2376",
    "Rank": "Spr",
    "Embarkation Dates": "M 40",
    "Marital Status": "M",
    "Enlistment": "Dargaville",
    "Occupation": "Carrier",
    "Address": "Dargaville",
    "Next of Kin": "Mrs Q B Vennell, Dargaville w",
    "Date of Birth": "Fri Apr 10 1908 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Tue Feb 09 1993 210000 GMT1300 New Zealand Daylight Time",
    "Age": "84",
    "Husbands/Wives/Partners": "Queenie Beatrice Kuini Price Elizabeth Inez Vennell",
    "Place of birth": "Ohingaiti",
    "Place of death": "Tauranga",
    "AL": "Y",
    "Notes": "Brother of Herbert George Vennell, who served in the Home Guard. Son of Edward Arthur and Alice May Vennell, nee Coyle. Husband of Queenie Beatrice (Kuini) Vennell, nee Price, of Dargaville. Husband of Elizabeth Inez Vennell. Place of birth: Ohingaiti. Place of death: Tauranga. Geni.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Vennell",
    "Christian Name": "Arthur Henry",
    "Unit": "2 Div N Z E",
    "Regtl. Number": "2376",
    "Rank": "WOII",
    "Embarkation Dates": "J 44-M 44",
    "Marital Status": "M",
    "Enlistment": "Dargaville",
    "Occupation": "Carrier",
    "Address": "Dargaville",
    "Next of Kin": "Mrs Q B Vennell, Dargaville w",
    "Date of Birth": "Fri Apr 10 1908 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Tue Feb 09 1993 210000 GMT1300 New Zealand Daylight Time",
    "Age": "84",
    "Husbands/Wives/Partners": "Queenie Beatrice Kuini Price Elizabeth Inez Vennell",
    "Place of birth": "Ohingaiti",
    "Place of death": "Tauranga",
    "AL": "Y",
    "Notes": "Brother of Herbert George Vennell, who served in the Home Guard. Son of Edward Arthur and Alice May Vennell, nee Coyle. Husband of Queenie Beatrice (Kuini) Vennell, nee Price, of Dargaville. Husband of Elizabeth Inez Vennell. Place of birth: Ohingaiti. Place of death: Tauranga. Geni.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Vercoe",
    "Christian Name": "Alfred George",
    "Unit": "Base Depot",
    "Regtl. Number": "31550",
    "Rank": "Pte",
    "Embarkation Dates": "J 40",
    "Marital Status": "S",
    "Enlistment": "Dargaville",
    "Occupation": "Grocer s assistant",
    "Address": "30 Victoria St, Dargaville",
    "Next of Kin": "Mrs A P Vercoe, Junction Rd, Paeroa m",
    "Date of Birth": "Fri May 24 1912 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sat Oct 10 1964 190000 GMT1200 New Zealand Daylight Time",
    "Age": "52",
    "Cemetery/Urupa and Where Known Plot Number": "Te Awamutu Cemetery Te Awamutu RSA Lawn Block 1A Row 5 Plot 126",
    "Place of birth": "Paeroa",
    "Place of death": "Te Awamutu",
    "AL": "Y",
    "Notes": "Son of Alfred William James and Agnes Price Vercoe, nee Adamson, of Paeroa. Last address: 81 Kihikihi Rd, Te Awamutu. Place of birth: Paeroa. Place of death: Te Awamutu. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Verner",
    "Christian Name": "James Leonard",
    "Unit": "N Z E",
    "Name Variation": "Verner, Len",
    "Regtl. Number": "17833",
    "Rank": "Spr",
    "Embarkation Dates": "A 41- J 41",
    "Marital Status": "M",
    "Enlistment": "Masterton",
    "Occupation": "Foreman",
    "Address": "17 Teviot St, Invercargill",
    "Next of Kin": "Mrs C I Verner, P.O., Clarence Bridge w",
    "Last rank Held": "L Sgt",
    "Date of Birth": "Mon Jul 22 1912 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Thu Feb 25 1982 210000 GMT1300 New Zealand Daylight Time",
    "Age": "69",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Thu Jul 07 1983 19 00 00 GMT 1200 New Zealand Standard Time",
    "Cemetery/Urupa and Where Known Plot Number": "Maunu Cemetery Whangarei Maunu Ash Berm Block A Plot 167",
    "Funeral Director": "Morris Morris Whg",
    "Husbands/Wives/Partners": "Constance Isabel Connie Gill",
    "Place of birth": "Otorohanga",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "MID. Son of Thomas Ferguson and Alice Maud Verner, nee Cater. Husband of Constance Isabel (Connie) Verner, nee Gill, per the Marriage Index, of Clarence Bridge. Place of birth: Otorohanga. Place of death: Whangarei. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Vesey",
    "Christian Name": "James Phillip",
    "Unit": "Inf Bde",
    "Name Variation": "Vesey, James Phillips",
    "Regtl. Number": "444553",
    "Rank": "Pte",
    "Embarkation Dates": "J 44-M 44",
    "Marital Status": "S",
    "Enlistment": "Kawakawa",
    "Occupation": "Labourer",
    "Address": "Pakaraka",
    "Next of Kin": "Mrs E M Vesey, Pakaraka m",
    "Date of Birth": "Tue Feb 13 1923 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Thu Dec 25 2008 210000 GMT1300 New Zealand Daylight Time",
    "Age": "85",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Manukau Memorial Gardens Manukau Lot AANON-X-002",
    "Husbands/Wives/Partners": "Beryl Irene Allan",
    "Place of birth": "Kawakawa",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "Son of Thomas Hernon (Hernan) and (Ethel) Mildred Vezey, nee Phillips, of Pakaraka. Husband of Beryl Irene Vezey, nee Allan. Place of birth: Kawakawa. Place of death: Auckland. James Phillips Vezey is as per the Birth Index. Familysearch.org. Ancestrylibrary.com.au. Myheritage.com"
  },
  {
    "Surname": "Vickery",
    "Christian Name": "Henry Bruce",
    "Unit": "24 Auck",
    "Name Variation": "Vickery, Bruce",
    "Regtl. Number": "24353",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Kaikohe",
    "Occupation": "Labourer",
    "POW": "Y",
    "Place of capture": "Unknown",
    "Address": "Kerikeri",
    "Next of Kin": "Mr H F Vickery, The Pines, Belmont Rd, Lower Hutt f",
    "Date of Birth": "Mon Apr 17 1916 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Jun 25 2007 190000 GMT1200 New Zealand Standard Time",
    "Age": "91",
    "AL": "Y",
    "Notes": "POW. Son of Henry Francis and Isabel Dorothy Vickery, of Lower Hutt. On the Birth index as Bruce Vickery. Two profiles on Cenotaph database. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Vipond",
    "Christian Name": "James Isaac",
    "Unit": "2 Div N Z E",
    "Regtl. Number": "239250",
    "Rank": "L Cpl",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "S",
    "Enlistment": "Kawakawa",
    "Occupation": "Quarry contractor",
    "Address": "Kawakawa",
    "Next of Kin": "Mrs S C Vipond, Matakana f",
    "Date of Birth": "Tue Jul 17 1906 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Fri Aug 27 1976 190000 GMT1200 New Zealand Standard Time",
    "Age": "70",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Kaikohe Cemetery RSA Block C Plot 322",
    "Funeral Director": "Unknown",
    "Husbands/Wives/Partners": "Esme Nellie Woodcock",
    "Place of birth": "Picton",
    "Place of death": "Kaikohe",
    "AL": "Y",
    "Notes": "Son of Spencer Carr and Miriam Agnes Vipond, nee Landall, of Matakana. Husband of Esme Nellie Vipond, nee Woodcock. Place of birth: Picton. Place of death: Kaikohe. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Viskovich",
    "Christian Name": "Arthur William David",
    "Unit": "N Z A S C",
    "Name Variation": "Viskovich, Vic",
    "Regtl. Number": "617679",
    "Rank": "T Cpl",
    "Embarkation Dates": "Jan 46-Jun 48",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Driver",
    "Address": "41 St. George's Bay Rd, Parnell, Auckland",
    "Next of Kin": "Mrs I Viskovich, 41 St. George's Bay Rd, Parnell, Auckland m",
    "Date of Birth": "Sat Dec 09 1922 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Mon Apr 16 1973 200000 GMT1200 New Zealand Standard Time",
    "Age": "50",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Waikumete Cemetery Glen Eden Auckland ROMAN CATHOLIC LAWN C Row 4 Plot 89",
    "Funeral Director": "Fletcher Brown Funeral Services",
    "Husbands/Wives/Partners": "Edna Viskovich",
    "Place of birth": "Northland",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "Brother of Ivan Mervyn Viskovich, who also served. Son of Ivan (John/Jack) and Constance Davina Connie Viskovich, nee Snodgrass, of Parnell, Auckland. Husband of Edna Viskovich. Place of birth: Northland. Place of death: Auckland. Geni.com. Familysearch.org. Ancestrylibrary.com.au. https://www.findagrave.com/memorial/181490217/ivan-viskovich ."
  },
  {
    "Surname": "Viskovich",
    "Christian Name": "Ivan Mervyn",
    "Unit": "3 Div Arty",
    "Name Variation": "Viskovich, Jack",
    "Regtl. Number": "266099",
    "Rank": "Gnr",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Shop Asst",
    "Address": "14 Portland Rd, Whangarei",
    "Next of Kin": "Mrs C Viskovich, 14 Portland Rd, Whangarei m",
    "Date of Birth": "Tue Feb 08 1921 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Fri Sep 29 2000 190000 GMT1200 New Zealand Standard Time",
    "Age": "79",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Tue Oct 03 2000 20 00 00 GMT 1300 New Zealand Daylight Time",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Morris Morris Whg",
    "Husbands/Wives/Partners": "Jocelyn Margaret Molloy Elsie Dawn Stokes",
    "Place of birth": "Ruakaka",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "Brother of Arthur William David Viskovich, who also served. Son of Ivan (John/Jack) and Constance Davina Connie Viskovich, nee Snodgrass, of Whangarei. Husband of Jocelyn Margaret Viskovich, nee Molloy and Elsie Dawn Viskovich, nee Stokes. Regimental number corrected as per Erratum on Nominal Roll. Place of birth: Ruakaka. Place of death: Whangarei. Cremated at Maunu Cemetery & Crematorium, Whangarei; no other information. Geni.com. Ancestrylibrary.com.au. https://www.findagrave.com/memorial/181490217/ivan-viskovich . http://www.roefamilytree.info/getperson.php?personID I3378&tree roe"
  },
  {
    "Surname": "Voelcker",
    "Christian Name": "Francis William",
    "Unit": "30 Bn",
    "Regtl. Number": "28089",
    "Rank": "Mjr",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "M",
    "Enlistment": "Whangarei",
    "Occupation": "Civil servant",
    "Address": "Kerikeri Central",
    "Next of Kin": "Mrs Daisy Norah Voelcker, Kerikeri Central wife",
    "Date of Birth": "Fri Oct 09 1896 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat May 22 1954 190000 GMT1200 New Zealand Standard Time",
    "Age": "57",
    "Burial/Cremation": "Cremation",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Watney Sibuns and Sons Limited",
    "Husbands/Wives/Partners": "Daisy Norah Hodgson",
    "Place of birth": "Kensington Middlesex England",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "Son of Edward William and Jessie McCaskie Voelcker, nee Beattie. Husband of Daisy Norah Voelcker, nee Hodgson, of Kerikeri Central. Wife s initials are D S in the NOK details. Cremated at Waikumete Cemetery & Crematorium, Glen Eden, Auckland; no other information. Place of birth: Kensington, Middlesex, England. Place of death: Auckland. Ancestry.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Voelcker",
    "Christian Name": "Francis William",
    "Unit": "Inf Bde",
    "Regtl. Number": "28089",
    "Rank": "Lt Col",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "M",
    "Enlistment": "Whangarei",
    "Occupation": "Civil Servant",
    "Address": "Kerikeri Central",
    "Next of Kin": "Mrs D S Voelcker, Kerikeri Central w",
    "Date of Birth": "Fri Oct 09 1896 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat May 22 1954 190000 GMT1200 New Zealand Standard Time",
    "Age": "57",
    "Burial/Cremation": "Cremation",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Watney Sibuns and Sons Limited",
    "Husbands/Wives/Partners": "Daisy Norah Hodgson",
    "Place of birth": "Kensington Middlesex England",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "Son of Edward William and Jessie McCaskie Voelcker, nee Beattie. Husband of Daisy Norah Voelcker, nee Hodgson, of Kerikeri Central. Wife s initials are D S in the NOK details. Cremated at Waikumete Cemetery & Crematorium, Glen Eden, Auckland; no other information. Place of birth: Kensington, Middlesex, England. Place of death: Auckland. Ancestry.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Voelcker",
    "Christian Name": "Francis William",
    "Unit": "Inf Bde",
    "Regtl. Number": "28089",
    "Rank": "Lt Col",
    "Embarkation Dates": "J 44-M 44",
    "Marital Status": "M",
    "Enlistment": "Whangarei",
    "Occupation": "Civil servant",
    "Address": "Kerikeri Central",
    "Next of Kin": "Mrs D N Voelcker, Kerikeri Central w",
    "Date of Birth": "Fri Oct 09 1896 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat May 22 1954 190000 GMT1200 New Zealand Standard Time",
    "Age": "57",
    "Burial/Cremation": "Cremation",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Watney Sibuns and Sons Limited",
    "Husbands/Wives/Partners": "Daisy Norah Hodgson",
    "Place of birth": "Kensington Middlesex England",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "Son of Edward William and Jessie McCaskie Voelcker, nee Beattie. Husband of Daisy Norah Voelcker, nee Hodgson, of Kerikeri Central. Wife s initials are D S in the NOK details. Cremated at Waikumete Cemetery & Crematorium, Glen Eden, Auckland; no other information. Place of birth: Kensington, Middlesex, England. Place of death: Auckland. Ancestry.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Voelcker",
    "Christian Name": "Francis William",
    "Unit": "Inf Bde",
    "Regtl. Number": "28089",
    "Rank": "Lt Col",
    "Embarkation Dates": "A 44-D 44",
    "Marital Status": "M",
    "Enlistment": "Whangarei",
    "Occupation": "Civil servant",
    "Address": "Kerikeri Central",
    "Next of Kin": "Mrs D N Voelcker, Kerikeri Central w",
    "Date of Birth": "Fri Oct 09 1896 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat May 22 1954 190000 GMT1200 New Zealand Standard Time",
    "Age": "57",
    "Burial/Cremation": "Cremation",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Watney Sibuns and Sons Limited",
    "Husbands/Wives/Partners": "Daisy Norah Hodgson",
    "Place of birth": "Kensington Middlesex England",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "Son of Edward William and Jessie McCaskie Voelcker, nee Beattie. Husband of Daisy Norah Voelcker, nee Hodgson, of Kerikeri Central. Wife s initials are D S in the NOK details. Cremated at Waikumete Cemetery & Crematorium, Glen Eden, Auckland; no other information. Place of birth: Kensington, Middlesex, England. Place of death: Auckland. Ancestry.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Vogt",
    "Christian Name": "Iris Evelyn",
    "Unit": "W A A C",
    "Name Variation": "See Howes, Iris Evelyn",
    "Regtl. Number": "812310",
    "Rank": "Pte",
    "Embarkation Dates": "J 43- D 43",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Farm worker",
    "Rolls": "WAAC",
    "Address": "P O Box 150, Kaikohe",
    "Next of Kin": "Mrs J E Howse, P O Box 150, Kaikohe m",
    "Last rank Held": "N K",
    "Date of Birth": "Tue Dec 09 1919 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat Jul 31 2010 190000 GMT1200 New Zealand Standard Time",
    "Age": "90",
    "Burial/Cremation": "Cremation",
    "Cemetery/Urupa and Where Known Plot Number": "Pyes Pa Cemetery Tauranga Pyes Pa 24559",
    "Funeral Director": "Jones Company Funeral Services",
    "Husbands/Wives/Partners": "Donald Stanley Vogt",
    "Place of birth": "Kaikohe",
    "Place of death": "Tauranga",
    "AL": "Y",
    "Notes": "Sister of David Roland Howse, who also served. Wife of Donald Stanley Vogt, who also served. Daughter of Albert and Jessie Evelyn Howse, nee Jackson (Stratford) of Kaikohe. Death recorded as Iris Evelyn Vogt. Place of birth: Kaikohe. Place of death: Tauranga. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Vogt",
    "Christian Name": "Iris Evelyn",
    "Unit": "W A A C",
    "Name Variation": "See Howes, Iris Evelyn",
    "Regtl. Number": "812310",
    "Rank": "Pte",
    "Embarkation Dates": "A 44-D 44",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Farmhand",
    "Rolls": "WAAC",
    "Address": "P O Box 150, Kaikohe",
    "Next of Kin": "Mrs J E Howse, P O Box 150, Kaikohe m",
    "Date of Birth": "Tue Dec 09 1919 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat Jul 31 2010 190000 GMT1200 New Zealand Standard Time",
    "Age": "90",
    "Burial/Cremation": "Cremation",
    "Cemetery/Urupa and Where Known Plot Number": "Pyes Pa Cemetery Tauranga Pyes Pa 24559",
    "Funeral Director": "Jones Company Funeral Services",
    "Husbands/Wives/Partners": "Donald Stanley Vogt",
    "Place of birth": "Kaikohe",
    "Place of death": "Tauranga",
    "AL": "Y",
    "Notes": "Sister of David Roland Howse, who also served. Wife of Donald Stanley Vogt, who also served. Daughter of Albert and Jessie Evelyn Howse, nee Jackson (Stratford) of Kaikohe. Death recorded as Iris Evelyn Vogt. Place of birth: Kaikohe. Place of death: Tauranga. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Voss",
    "Christian Name": "Alfred John",
    "Unit": "Inf Reinfs",
    "Regtl. Number": "29835",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "M",
    "Enlistment": "Tauranga",
    "Occupation": "Farmer",
    "Address": "Post Office, Tauranga",
    "Next of Kin": "Mrs Eileen Alice Voss, C - J K Hamilton, Rural Delivery, Tauranga wife",
    "Date of Birth": "Thu Oct 03 1918 183000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat Mar 01 1997 210000 GMT1300 New Zealand Daylight Time",
    "Age": "78",
    "Cemetery/Urupa and Where Known Plot Number": "Oropi Cemetery Tauranga Block D Plot 6",
    "Husbands/Wives/Partners": "Eileen Alice Hamilton",
    "Place of birth": "Mickleham England or Dorking Surrey England",
    "AL": "Y",
    "Notes": "DCM. MC. MBE (Mil). Son of Alfred Stanley and Gladys Jessie Louise Voss, nee Newton. Husband of Eileen Alice Voss, nee Hamilton, (Hewitt) of Tauranga. Rejoined the Army in 1950. MBE relating to the Malaya campaign. Last known rank - Major. Resident in Whangarei for many years. Place of birth: Mickleham, England, or Dorking, Surrey, England. Credit: Janet Brown, and Helen Towgood, daughters. Plot no. Is unknown. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Vujcich",
    "Christian Name": "Alfred Matthew Anthony",
    "Unit": "Inf Reinfs",
    "Name Variation": "Vujcich, Alf",
    "Regtl. Number": "29761",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Kawakawa",
    "Occupation": "Storeman",
    "Address": "Whirinaki",
    "Next of Kin": "Mr Mate Vujcich, Whirinaki father",
    "Last rank Held": "Pte",
    "Date of Birth": "Thu Nov 21 1918 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Mon Mar 03 2008 210000 GMT1300 New Zealand Daylight Time",
    "Age": "89",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "RSA Block Twenty B Plot 1360 Maunu",
    "Funeral Director": "Morris Morris Whg",
    "Husbands/Wives/Partners": "Marjory Joan Humphrey",
    "Place of birth": "Southwark Surrey England",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "Brother of Ronald Ivan Gregory Vujcich, who also served. Son of Matthew (Mate) Vujcich and Lilian May Vujcich, nee Packer, of Kaitaia. Husband of Marjory Joan Vujcich, nee Humphrey. Place of birth: Southwark, Surrey, England. Place of death: Whangarei. Geni.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Vujcich",
    "Christian Name": "Ronald Ivan Gregory",
    "Unit": "4th Armd Bde",
    "Name Variation": "Vujcich, Ron",
    "Regtl. Number": "83313",
    "Rank": "Tpr",
    "Embarkation Dates": "A 43-J 43",
    "Marital Status": "M",
    "Enlistment": "Rawene",
    "Occupation": "Truck Driver",
    "Address": "P B, Rawene",
    "Next of Kin": "Mrs J E Vujcich, P B, Rawene w",
    "Last rank Held": "Tpr",
    "Date of Birth": "Sun Mar 27 1921 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Tue Sep 19 2006 190000 GMT1200 New Zealand Standard Time",
    "Age": "85",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Hamilton Park Cemetery Hamilton OAK-13-61",
    "Funeral Director": "Pellows Funeral Services",
    "Husbands/Wives/Partners": "Joyce Ethel Pearson",
    "Place of birth": "Whirinaki",
    "Place of death": "Atawhai Assisi Rest Home Hamilton",
    "AL": "Y",
    "Notes": "Brother of Alfred Matthew Anthony Vujcich, who also served. Son of Matthew (Mate) Vujcich and Lilian May Vujcich, nee Packer, of Kaitaia. Husband of Joyce Ethel Vujcich, nee Pearson, of Rawene. Place of birth: Whirinaki. Place of death: Atawhai Assisi Rest Home, Matangi. Date of birth on burial record shown as 27 Mar 1921. Geni.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Vukovich",
    "Christian Name": "Matey George",
    "Unit": "A Tk Bde",
    "Name Variation": "Vukovich, Mate Jure",
    "Regtl. Number": "83163",
    "Rank": "Tpr",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "M",
    "Enlistment": "Auckland",
    "Occupation": "Carpenter",
    "Address": "14 Edinburgh St, Pukekohe",
    "Next of Kin": "Mrs M G Vukovich, C - Mrs T Garea, P O Dargaville w",
    "Date of Birth": "Sat Aug 26 1916 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Sep 02 1985 190000 GMT1200 New Zealand Standard Time",
    "Age": "69",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Waikumete Cemetery Glen Eden Auckland Roman Catholic Berm A Row 10 Plot 81",
    "Funeral Director": "Fletcher Brown Funeral Services",
    "Husbands/Wives/Partners": "Perina Sunde",
    "AL": "Y",
    "Notes": "Son of Jure and Perina Vukovich. Husband of Mrs M G Vukovich, of Dargaville. Jure Vukovich appears on the Marriage Index; wife is there shown as Perina Sunde. Likely to be this person. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Vyle",
    "Christian Name": "Arthur Maurice",
    "Unit": "Armd Bde",
    "Regtl. Number": "170868",
    "Rank": "Tpr",
    "Embarkation Dates": "J 44-M 44",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Farm hand",
    "Address": "Otaika, Whangarei",
    "Next of Kin": "Mrs M Vyle, Otaika, Whangarei m",
    "Date of Birth": "Tue Jun 01 1920 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "2001",
    "Age": "81",
    "Husbands/Wives/Partners": "Doreen Mitchell",
    "Place of birth": "Whangarei",
    "Place of death": "Australia",
    "AL": "Y",
    "Notes": "Son of Edmund Arthur Ted Eddy and Mabel Vyle, nee North, of Whangarei. Husband of Doreen Vyle, nee Mitchell. Attended WBHS 1933-35. Place of birth: Whangarei. Place of death: Australia. Familysearch.org. Ancestrylibrary.com.au. https://wbhsoba.co.nz/wp-content/uploads/1933.pdf"
  }
];