const veteransDataI = [
  {
    "Surname": "Iggulden",
    "Christian Name": "Lloyd Alfred George",
    "Unit": "N Z M C",
    "Regtl. Number": "616416",
    "Rank": "Pte",
    "Embarkation Dates": "J 44-M 44",
    "Marital Status": "S",
    "Enlistment": "Wellington",
    "Occupation": "Farmhand",
    "Address": "Moonshine Rd, Pahautanui",
    "Next of Kin": "Mrs O A Iggulden, Beech Rd, Te Horo m",
    "Date of Birth": "Sun Jul 16 1922 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sat Dec 06 2003 210000 GMT1300 New Zealand Daylight Time",
    "Age": "81",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Wed Dec 10 2003 21 00 00 GMT 1300 New Zealand Daylight Time",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Newberrys Whg",
    "Place of birth": "Pauatahanui Porirua",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "Son of Thomas Edward and Olive Amelia Iggulden, nee Galloway, of Te Horo. Cremated at Maunu Cemetery, Whangarei; no other information. Place of birth: Pauatahanui, Porirua. Place of death: Whangarei. Ancestrylibrary.com.au. https://poriruawarstories.com/iggulden-thomas-edward"
  },
  {
    "Surname": "Ihaka",
    "Christian Name": "Ngawati",
    "Unit": "28 Maori",
    "Name Variation": "See under Ihaka, Wati",
    "Regtl. Number": "25890",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Kaikohe",
    "Occupation": "Labourer",
    "POW": "Y",
    "Place of capture": "Crete",
    "Address": "Kaikohe",
    "Next of Kin": "Miss E Ihaka, Pawarenga s",
    "Last rank Held": "Pte",
    "Date of Birth": "Fri Feb 13 1914 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sun May 15 1983 190000 GMT1200 New Zealand Standard Time",
    "Age": "69",
    "Husbands/Wives/Partners": "Cecelia Celia Hiria Abraham",
    "Place of birth": "Mangamuka",
    "Place of death": "Ahipara",
    "AL": "Y",
    "Notes": "POW. Husband of Cecelia, (Celia) (Hiria) Ihaka, nee Abraham. Brother of Miss E Ihaka, of Pawarenga. 1981 Northern Maori Electoral Rolls. Almost certainly this person who is shown as Ngawati Ihaka, on Ancestry.com.au. Place of birth: Mangamuka. Place of death: Ahipara."
  },
  {
    "Surname": "Ihaka",
    "Christian Name": "Rawhiti",
    "Unit": "28 Maori",
    "Name Variation": "Ihaka, Te Rawhiti Eru Ihaka, Shack",
    "Regtl. Number": "39352",
    "Rank": "T S Sgt",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Te Kao",
    "Occupation": "Labourer",
    "POW": "Y",
    "Place of capture": "Greece",
    "Address": "Te Kao",
    "Next of Kin": "Mrs P Ihaka, Te Kao m",
    "Last rank Held": "T S Sgt",
    "Date of Birth": "Sat Nov 09 1912 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Tue Jun 23 1981 190000 GMT1200 New Zealand Standard Time",
    "Age": "68",
    "Husbands/Wives/Partners": "Raihamahirau Kaaka",
    "Place of birth": "Te Kao",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "POW. Brother Reweti Ihaka, served and was killed in action and brother Riki Reihana Ihaka, also served. Son of Eru Timoko and Te Paea Reewe Ihaka, nee Hinks, of Te Kao. Husband of Raihamahirau Ihaka, nee Kaaka. Place of birth: Te Kao. Place of death: Auckland. On the Death Index as Te Rawhiti Ihaka. Notes on Maori Battalion website. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Ihaka",
    "Christian Name": "Reweti",
    "Unit": "28 Maori",
    "Regtl. Number": "62732",
    "Rank": "Cpl",
    "Embarkation Dates": "A 41- J 41",
    "Marital Status": "S",
    "Enlistment": "Kaitaia",
    "Occupation": "Labourer",
    "Address": "Te Kao",
    "Next of Kin": "Mrs T P Ihaia, Te Kao, m",
    "Where Killed or Died": "West Des",
    "Cemetery Name": "Alamein Memorial El Alamein War Egypt",
    "Grave/Memorial Reference": "Column 101",
    "Last rank Held": "Sgt",
    "Date of Birth": "Fri Jul 05 1918 183000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Nov 02 1942 190000 GMT1200 New Zealand Daylight Time",
    "Age": "24",
    "Burial/Cremation": "--",
    "Place of birth": "Te Kao",
    "AL": "Y",
    "Notes": "Brother of Rawhiti and Riki Reihana Ihaka, who also served. Son of Eru Timoko and Te Paea Reewe Ihaka, nee Hinks, of Te Kao. Comments and memories are on the Maori Battalion website. On the Kaitaia War Memorial. Place of birth: Te Kao. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Ihaka",
    "Christian Name": "Riki Reihana",
    "Unit": "H Q 28 Maori",
    "Regtl. Number": "39354",
    "Rank": "Pte",
    "Embarkation Dates": "J 40",
    "Marital Status": "S",
    "Enlistment": "Kaitaia",
    "Occupation": "Labourer",
    "POW": "Y",
    "Place of capture": "Greece",
    "Address": "Te Kao",
    "Next of Kin": "Mrs Tepaea Ihaka, Te Kao m",
    "Last rank Held": "Pte",
    "Date of Birth": "Wed Apr 18 1917 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Wed Aug 08 1984 190000 GMT1200 New Zealand Standard Time",
    "Age": "67",
    "Place of birth": "Te Kao",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "POW. Brother of Reweti Ihaka who served and fell and Rawhiti Ihaka, who also served. Son of Eru Timoko and Te Paea Reewe Ihaka, nee Hinks, of Te Kao. Place of birth: Te Kao. Place of death: Auckland. Comments on Maori Battalion website. Geni.com. Name on Birth Index is Reihana Ihaka. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Ihaka",
    "Christian Name": "Wati",
    "Unit": "28 Maori",
    "Name Variation": "Ihaka, Ngawati",
    "Regtl. Number": "25890",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Kaikohe",
    "Occupation": "Labourer",
    "POW": "Y",
    "Place of capture": "Crete",
    "Address": "Kaikohe",
    "Next of Kin": "Miss E Ihaka, Pawarenga s",
    "Last rank Held": "Pte",
    "Date of Birth": "Fri Feb 13 1914 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sun May 15 1983 190000 GMT1200 New Zealand Standard Time",
    "Age": "69",
    "Husbands/Wives/Partners": "Cecelia Celia Hiria Abraham",
    "Place of birth": "Mangamuka",
    "Place of death": "Ahipara",
    "AL": "Y",
    "Notes": "POW. Husband of Cecelia, (Celia) (Hiria) Ihaka, nee Abraham. Brother of Miss E Ihaka, of Pawarenga. 1981 Northern Maori Electoral Rolls. Almost certainly this person who is shown as Ngawati Ihaka, on Ancestry.com.au. Place of birth: Mangamuka. Place of death: Ahipara"
  },
  {
    "Surname": "Ihaka",
    "Christian Name": "Wiremu",
    "Unit": "28 Maori",
    "Name Variation": "Ihaka, Wiremu Te Iwa Ihaka, Wiremu Te Iwa Nine",
    "Regtl. Number": "39355",
    "Rank": "L Cpl",
    "Embarkation Dates": "A 41- J 41",
    "Marital Status": "M",
    "Enlistment": "Kaitaia",
    "Occupation": "Labourer",
    "Address": "Pawarenga",
    "Next of Kin": "Mrs J Ihaka, Pawarenga w",
    "Last rank Held": "L Cpl",
    "Date of Birth": "Wed Sep 02 1908 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Fri May 10 1985 190000 GMT1200 New Zealand Standard Time",
    "Age": "76",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Rotokakahi Pawarenga",
    "Husbands/Wives/Partners": "Mihiwera Julia Rudolph",
    "Place of birth": "Kaitaia",
    "Place of death": "Kaitaia",
    "AL": "Y",
    "Notes": "Husband of (Mihiwera) Julia Ihaka, nee Rudolph, per the Marriage Index, of Pawarenga. Comments on Maori Battalion file. Wiremu Te Iwa Niwa Ihaka is as per the Find a Grave website. Place of birth: Kaitaia. Place of death: Kaitaia. Possible information on MyHeritage.com. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Ihimaera",
    "Christian Name": "Waata Thomas",
    "Unit": "Inf Reinfs",
    "Name Variation": "Ihimaera, Walter Ihimaera- James, Walter Thomas Ihimaera, Walter Thomas",
    "Regtl. Number": "67806",
    "Rank": "Pte",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "S",
    "Enlistment": "Auckland",
    "Occupation": "Labourer",
    "Address": "C - Swanson Grill Rooms, Swanson Street, Auckland",
    "Next of Kin": "Mrs B James, Mamaranui m",
    "Last rank Held": "Pte",
    "Date of Birth": "See note",
    "Date of Death": "Fri Oct 08 1971 190000 GMT1200 New Zealand Standard Time",
    "Age": "-----",
    "Cemetery/Urupa and Where Known Plot Number": "Urupa St James Anglican Church Mangere Bridge Auckland",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "Son of Waehaere (Te Wae Wae) Kaohua/Robert (Ropata) (James) Haratua and Towai (Becky) (Beckie) Ihimaera, nee Haira. Mrs B James, of Mamaranui, is as per the NOK details. Place of death: Auckland. Headstone has the name Walter. Note on Maori Battalion website. 1954 Northern Maori Roll. Ancestry.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Imms",
    "Christian Name": "Arthur Kitchener",
    "Unit": "Arty Reinf 8 Bde Gp",
    "Regtl. Number": "71919",
    "Rank": "Gnr",
    "Embarkation Dates": "O 41- D 41",
    "Marital Status": "S",
    "Enlistment": "Wellington",
    "Occupation": "Farm hand",
    "Address": "Kamo Rd, Whangarei",
    "Next of Kin": "Mrs C Imms, Kamo Rd, Whangarei m",
    "Last rank Held": "Gnr",
    "Date of Birth": "Wed Nov 10 1920 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Thu Nov 07 1991 210000 GMT1300 New Zealand Daylight Time",
    "Age": "70",
    "Burial/Cremation": "Burial",
    "Ashes/Burial": "Mon Nov 11 1991 21 00 00 GMT 1300 New Zealand Daylight Time",
    "Cemetery/Urupa and Where Known Plot Number": "Kerikeri Wiroa Cemetery Block X Plot 2",
    "Funeral Director": "Squires Funeral Services",
    "Husbands/Wives/Partners": "Evelyn Jean Pearson",
    "Place of birth": "NZ",
    "Place of death": "Northland Base Hospital Whangarei",
    "AL": "Y",
    "Notes": "Brother of Charles Edward Imms, who also served and James Henry Imms, who served with the R.N.Z.A.F. Son of William and Clara Imms, nee Moors, of Whangarei. Husband of Evelyn Jean Imms, nee Pearson. Place of birth: Whangarei. Place of death: Northland Base Hospital, Whangarei. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Imms",
    "Christian Name": "Arthur Kitchener",
    "Unit": "N Z A",
    "Regtl. Number": "71919",
    "Rank": "Gnr",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "S",
    "Enlistment": "Wellington",
    "Occupation": "Farm hand",
    "Address": "Kamo",
    "Next of Kin": "Mrs C Imms, Kamo m",
    "Last rank Held": "Gnr",
    "Date of Birth": "Wed Nov 10 1920 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Thu Nov 07 1991 210000 GMT1300 New Zealand Daylight Time",
    "Age": "70",
    "Burial/Cremation": "Burial",
    "Ashes/Burial": "Mon Nov 11 1991 21 00 00 GMT 1300 New Zealand Daylight Time",
    "Cemetery/Urupa and Where Known Plot Number": "Kerikeri Wiroa Cemetery Block X Plot 2",
    "Funeral Director": "Squires Funeral Services",
    "Husbands/Wives/Partners": "Evelyn Jean Pearson",
    "Place of birth": "NZ",
    "Place of death": "Northland Base Hospital Whangarei",
    "AL": "Y",
    "Notes": "Brother of Charles Edward Imms, who also served and James Henry Imms, who served with the R.N.Z.A.F. Son of William and Clara Imms, nee Moors, of Whangarei. Husband of Evelyn Jean Imms, nee Pearson. Place of birth: Whangarei. Place of death: Northland Base Hospital, Whangarei. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Imms",
    "Christian Name": "Charles Edward",
    "Unit": "35 Bn",
    "Regtl. Number": "68340",
    "Rank": "Pte",
    "Embarkation Dates": "J-M 42",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Dairy factory hand",
    "Address": "Kamo",
    "Next of Kin": "Mrs C Imms, Kamo m",
    "Date of Birth": "Thu Jul 31 1919 183000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Jan 18 1999 210000 GMT1300 New Zealand Daylight Time",
    "Age": "79",
    "Cemetery/Urupa and Where Known Plot Number": "Kauri Cemetery Whangarei",
    "Husbands/Wives/Partners": "Margaret Lillian Lewis then Wright",
    "Place of birth": "Okaihau",
    "Place of death": "Whangarei Hospital Whangarei",
    "AL": "Y",
    "Notes": "Brother of Arthur Kitchener Imms, who also served and James Henry Imms, who served with the R.N.Z.A.F. Son of William and Clara Imms, nee Moors, of Whangarei. Husband of Margaret Lillian Imms, formerly Wright, nee Lewis. Place of death: Whangarei Hospital, Whangarei. Place of birth: Okaihau."
  },
  {
    "Surname": "Imms",
    "Christian Name": "Charles Edward",
    "Unit": "H Q 35 Bn",
    "Regtl. Number": "68340",
    "Rank": "Pte",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Dairy Fact hand",
    "Address": "Kamo",
    "Next of Kin": "Mrs C Imms, Kamo m",
    "Date of Birth": "Thu Jul 31 1919 183000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Jan 18 1999 210000 GMT1300 New Zealand Daylight Time",
    "Age": "79",
    "Cemetery/Urupa and Where Known Plot Number": "Kauri Cemetery Whangarei",
    "Husbands/Wives/Partners": "Margaret Lillian Lewis then Wright",
    "Place of birth": "Okaihau",
    "Place of death": "Whangarei Hospital Whangarei",
    "AL": "Y",
    "Notes": "Brother of Arthur Kitchener Imms, who also served and James Henry Imms, who served with the R.N.Z.A.F. Son of William and Clara Imms, nee Moors, of Whangarei. Husband of Margaret Lillian Imms, formerly Wright, nee Lewis. Place of death: Whangarei Hospital, Whangarei. Place of birth: Okaihau."
  },
  {
    "Surname": "Ingham",
    "Christian Name": "Allan Gravenor",
    "Unit": "Inf Bde",
    "Name Variation": "Ingham, Allen Grosvenor",
    "Regtl. Number": "617230",
    "Rank": "Pte",
    "Embarkation Dates": "A 43-J 43",
    "Marital Status": "S",
    "Enlistment": "Te Awamutu",
    "Occupation": "Farm labourer",
    "Address": "C - Mrs A Berry, Pokuru, Te Hana, R.D.",
    "Next of Kin": "Mr W Ingham, Pokuru, Te Hana, R.D. f",
    "Date of Birth": "Mon Jan 05 1920 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sat Aug 11 2001 190000 GMT1200 New Zealand Standard Time",
    "Age": "81",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Wed Aug 15 2001 19 00 00 GMT 1200 New Zealand Standard Time",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Sadlier Funeral Services",
    "AL": "Y",
    "Notes": "Son of William and Gertrude Hannah Ingham, of Te Hana. On the cemetery index as Allan Grosvenor Ingham. Cremated at Hamilton Park Cemetery & Crematorium, Hamilton. Last address: Thames St, Morrinsville. No other information. Birth index is as per the nominal roll. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Ingram",
    "Christian Name": "Francis Lumsden",
    "Unit": "Arty Reinfs",
    "Regtl. Number": "28975",
    "Rank": "Gnr",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Kawakawa",
    "Occupation": "Motor mechanic",
    "Address": "P O Box 20, Rawene",
    "Next of Kin": "Mrs E Spender, Rawene mother",
    "Date of Birth": "Wed Jun 12 1918 183000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Aug 21 1995 190000 GMT1200 New Zealand Standard Time",
    "Age": "77",
    "AL": "Y",
    "Notes": "Son of David Christopher and Frances Edith Ingram (later Spender, of Rawene?), nee Millar. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Ingram",
    "Christian Name": "Harold Alexander",
    "Unit": "Inf Bde",
    "Regtl. Number": "612531",
    "Rank": "T S Sgt",
    "Embarkation Dates": "A 43-J 43",
    "Marital Status": "M",
    "Enlistment": "Wellington",
    "Occupation": "Tram conductor",
    "Address": "29 Wellington Rd, Wellington",
    "Next of Kin": "Mrs T J Ingram, 29 Wellington Rd, Wellington w",
    "Date of Birth": "Thu Sep 26 1912 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sun Sep 17 1995 190000 GMT1200 New Zealand Standard Time",
    "Age": "82",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Thu Sep 21 1995 19 00 00 GMT 1200 New Zealand Standard Time",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Newberrys Whg",
    "Husbands/Wives/Partners": "Thelma Josephine Hansen",
    "Place of birth": "Nelson",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "Son of John Bartlett (Jack) Welsh and Phoebe Maria Ingram, nee Davey. Husband of Thelma Josephine Ingram, nee Hansen, of Wellington. Cremated at Maunu Cemetery, Whangarei, no other information. Age incorrect on cemetery record. Place of birth: Nelson. Place of death: Whangarei. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Inwood",
    "Christian Name": "Alan Antonia",
    "Unit": "24 Auck",
    "Name Variation": "Inwood, Alan Antonio",
    "Regtl. Number": "24094",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Kaikohe",
    "Occupation": "Labourer",
    "POW": "Y",
    "Place of capture": "Unknown",
    "Address": "Kaikohe",
    "Next of Kin": "Mr P Inwood, Whangarei father",
    "Last rank Held": "Pte",
    "Date of Birth": "Wed Feb 05 1913 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Tue Sep 24 1996 190000 GMT1200 New Zealand Standard Time",
    "Age": "83",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "RSA Block Seventeen Plot 1201 Maunu",
    "Funeral Director": "Morris Morris Whg",
    "Husbands/Wives/Partners": "Doreen Harriet Mavis Litt",
    "Place of birth": "Westport",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "POW. Brother of Philip John Inwood, who also served. Son of Phillip Oscar and Mabel Jessie Inwood, nee Herbert, of Whangarei. Husband of Doreen Harriet Mavis Inwood, nee Litt. Place of birth: Westport. Place of death: Whangarei. Birth and death recorded as Alan Antonio Inwood. Place of death: Whangarei. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Inwood",
    "Christian Name": "Philip John",
    "Unit": "6 Fd Amb",
    "Regtl. Number": "12397",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "M",
    "Enlistment": "Taumarunui",
    "Occupation": "Labourer",
    "POW": "Y",
    "Place of capture": "Unknown",
    "Address": "Ohura, King Country",
    "Next of Kin": "Mrs M Inwood, 43 Randwick Rd, Lower Hutt w",
    "Last rank Held": "Pte",
    "Date of Birth": "Wed Dec 27 1911 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Mon Nov 02 1981 210000 GMT1300 New Zealand Daylight Time",
    "Age": "69",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Maunu Cemetery Whangarei RSA Block Seventeen Plot 915",
    "Funeral Director": "Morris Morris Whg",
    "Husbands/Wives/Partners": "Adrienne Verna May Hopgood",
    "Place of birth": "Westport",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "POW. Brother of Alan Antonia (Antonio) Inwood, who also served. Son of Philip Oscar and Mabel Jessie Inwood, nee Herbert, of Whangarei. Husband of Adrienne Verna May Inwood, nee Hopgood, per the Marriage Index. Wife shown as Mrs M Inwood, of Lower Hutt, in the NOK details. Birth index in the name of Philip Inwood. Place of birth: Westport. Place of death: Whangarei. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Iraia",
    "Christian Name": "Te Whata",
    "Unit": "28 Maori",
    "Name Variation": "Iraia, W",
    "Regtl. Number": "39353",
    "Rank": "Pte",
    "Embarkation Dates": "J 40",
    "Marital Status": "S",
    "Enlistment": "Auckland",
    "Occupation": "Steelworker",
    "Address": "20 Edenvale Road, Mt Eden, Auckland,",
    "Next of Kin": "Mr Dave Iraia, Waimamaku, Hokianga b",
    "Where Killed or Died": "West Des",
    "Cemetery Name": "Alamein Memorial El Alamein War Egypt",
    "Grave/Memorial Reference": "Column 103",
    "Last rank Held": "Pte",
    "Date of Birth": "See note",
    "Date of Death": "Tue Dec 16 1941 200000 GMT1200 New Zealand Daylight Time",
    "Age": "35",
    "Burial/Cremation": "--",
    "Place of birth": "Waimamaku",
    "AL": "Y",
    "Notes": "Son of Rewi Iraia Mu ( Rewiri Te Kihi Mokena) and Kare Rewi (Hapakuku) Iraia, nee Moetara, of Waimamaku. Brother of Dave Iraia, of Waimamaru. Place of birth: Waimamaku. Bio on Cenotaph record. Served with A Company per 28 Maori Battalion museum.Ancestrylibrary.com.au shows birthdate as 1 November 1904."
  },
  {
    "Surname": "Irvine",
    "Christian Name": "Robert Arthur",
    "Unit": "2 Div Cav",
    "Regtl. Number": "659545",
    "Rank": "Tpr",
    "Embarkation Dates": "Jan 46-Jun 48",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Farm hand",
    "Address": "Pipiwai, R.D., Whangarei",
    "Next of Kin": "Mrs N H Irvine, Pipiwai, R.D., Whangarei m",
    "Last rank Held": "Cpl",
    "Date of Birth": "Wed Sep 08 1926 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sat Jan 30 2010 210000 GMT1300 New Zealand Daylight Time",
    "Age": "83",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Thu Feb 04 2010 21 00 00 GMT 1300 New Zealand Daylight Time",
    "Cemetery/Urupa and Where Known Plot Number": "North Shore Memorial Park Albany Plot Northern Division Rsa Ash Lawn Section 2 Block E Row A Plot 25",
    "Funeral Director": "Dils Funeral Services Ltd",
    "Husbands/Wives/Partners": "Gaynor Williams",
    "Place of birth": "Waipukurau",
    "Place of death": "Albany North Shore",
    "AL": "Y",
    "Notes": "Son of William Richard and Nora H Irvine, of Pipiwai. Husband of Gaynor Irvine, nee Williams. Date of death incorrect on Find a Grave website. Place of birth: Waipukurau. Place of death: Albany, North Shore. Ancestrylibrary.com.auhttps://knowledgebank.org.nz/text/robert-arthur-irvine-biography-1971/"
  },
  {
    "Surname": "Irving",
    "Christian Name": "Henry",
    "Unit": "Inf Reinfs",
    "Regtl. Number": "29342",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Auckland",
    "Occupation": "Sheet metal worker",
    "Address": "677 Remuera Road, Auckland",
    "Next of Kin": "Mrs A E Irving, 677 Remuera Road, Auckland m",
    "Where Killed or Died": "Crete",
    "Cemetery Name": "Suda Bay War Crete Greece",
    "Grave/Memorial Reference": "Plot 6 Row C Grave 1",
    "Last rank Held": "Pte",
    "Date of Birth": "Thu Oct 03 1918 183000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sun May 25 1941 200000 GMT1200 New Zealand Standard Time",
    "Age": "22",
    "Burial/Cremation": "--",
    "AL": "Y",
    "Notes": "Son of Percy Hamilton and Hannah Elizabeth Irving, nee Herbert, of Whangaroa. Mother s initials are A E in the NOK details. On the Meadowbank School Roll of Honour. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Irving",
    "Christian Name": "Leonard Sydney",
    "Unit": "Inf Bde",
    "Name Variation": "Irving, Lennard Sydney Irving, Leonard Sydney Rawene",
    "Regtl. Number": "441049",
    "Rank": "Pte",
    "Embarkation Dates": "J 44-M 44",
    "Marital Status": "S",
    "Enlistment": "Auckland",
    "Occupation": "Brass engineer",
    "Address": "Swanson, Auck.",
    "Next of Kin": "Mr L S Irving, Russell f",
    "Date of Birth": "Sun Sep 10 1922 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Wed Jul 06 1988 190000 GMT1200 New Zealand Standard Time",
    "Age": "65",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Russell Cemetery Russell RSA Division Plot 58",
    "Funeral Director": "Unknown",
    "Husbands/Wives/Partners": "Marara Mokaraka",
    "Place of birth": "Russell",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "Brother of Robert (Walter) Neha Irving, who also served. Son of Leonard Sidney (Hiri) and Ngaruia Pirihira Tunga (Louie Tonga) Irving, nee Paraone, (Brown), of Russell. Husband of Marara Irving, nee Mokaraka. Mother s name shown as Louie Tonga Irving on the Birth Index. Death index in the name of Lennard Sydney Irving. Name misspelt on Find a Grave website. Place of birth: Russell. Place of death: Auckland. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Irving",
    "Christian Name": "Robert Neha",
    "Unit": "H Q Inf Corps",
    "Name Variation": "Irving, Robert Walter Neha Irving, Bob",
    "Regtl. Number": "812812",
    "Rank": "Pte",
    "Embarkation Dates": "Jan 46-Jun 48",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Freez wks hnd",
    "Address": "P O Box 15, Russell",
    "Next of Kin": "Mrs L Irving, P O Box 15, Russell m",
    "Last rank Held": "Pte",
    "Date of Birth": "Sun Sep 11 1927 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Fri Mar 06 2009 210000 GMT1300 New Zealand Daylight Time",
    "Age": "81",
    "Burial/Cremation": "Burial",
    "Ashes/Burial": "Mon Mar 09 2009 20 00 00 GMT 1300 New Zealand Daylight Time",
    "Cemetery/Urupa and Where Known Plot Number": "Russell Cemetery Alphabet Section New Block G Plot 114",
    "Funeral Director": "Squires Funeral Services",
    "Place of birth": "Russell",
    "Place of death": "Russell",
    "AL": "Y",
    "Notes": "Brother of Leonard (Lennard) Sydney Irving, who also served. Son of Leonard Sidney (Hiri) and Ngaruia Pirihira Tunga (Louie Tonga) Irving, nee Paraone, (Brown), of Russell. Death recorded as Robert Walter Neha Irving. Note on cemetery record shows regimental number as 821821. Same on Cenotaph Record. Place of death, residence 29 Oneroa Rd, Russell. Place of birth and death: Russell. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Irwin",
    "Christian Name": "Harry Douglas",
    "Unit": "28 Maori",
    "Name Variation": "Irwin, Douglas",
    "Regtl. Number": "64685",
    "Rank": "Pte",
    "Embarkation Dates": "J 41-S 41",
    "Marital Status": "S",
    "Enlistment": "Samoa",
    "Occupation": "Soldier",
    "Address": "C - N.Z. Government Army Department, Auckland",
    "Next of Kin": "Mr H Irwin, Apia, Samoa, Pacific Islands f",
    "Last rank Held": "Pte",
    "Date of Birth": "Mon Apr 18 1921 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sat Apr 10 2004 190000 GMT1200 New Zealand Standard Time",
    "Age": "82",
    "Cemetery/Urupa and Where Known Plot Number": "Purewa Cemetery and Crematorium Meadowbank Auckland Block S Row 45 Plot 9",
    "Husbands/Wives/Partners": "Mary Merero Panapa",
    "Place of birth": "Apia Samoa",
    "Place of death": "Kaitaia",
    "AL": "Y",
    "Notes": "Son of Harry and Sina Tatopau Irwin, nee Salanoa, of Apia, Samoa. Husband of Mary (Merero) Irwin, nee Panapa. Place of death: Kaitaia. Place of birth: Apia, Samoa. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Isaac",
    "Christian Name": "Bill",
    "Unit": "28 Maori",
    "Name Variation": "Isaac, Wiremu Bill Ututaonga, Wiremu Bill",
    "Regtl. Number": "39669",
    "Rank": "Pte",
    "Embarkation Dates": "J 40",
    "Marital Status": "S",
    "Enlistment": "Kaikohe",
    "Occupation": "Labourer",
    "Address": "Pakaraka",
    "Next of Kin": "Mr D Ututaonga, Pakaraka b",
    "Last rank Held": "Pte",
    "Date of Birth": "Sun Feb 18 1923 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Wed Sep 03 1980 190000 GMT1200 New Zealand Standard Time",
    "Age": "57",
    "Husbands/Wives/Partners": "Lorraine Mary Bligh Parker",
    "Place of birth": "Taumarere Kawakawa",
    "Place of death": "Christchurch or Auckland",
    "AL": "Y",
    "Notes": "Brother of Paratene (Dan) and Wally (Walter) William (William Whare) Ututaonga, who also served. Son of Wiremu Ihaka Te HereHere and Ngakirikiri Ututaonga, nee Cherrington-Keretene). Husband of Lorraine Mary Bligh Isaac, nee Parker. Brother of Mr D Ututaonga, of Pakaraka. Place of birth: Taumarere, Kawakawa. Place of death: Christchurch or Auckland. Geni.com. MyHeritage.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Isaacs",
    "Christian Name": "Kiri",
    "Unit": "28 Maori",
    "Regtl. Number": "801658",
    "Rank": "Pte",
    "Embarkation Dates": "J 43- D 43",
    "Marital Status": "S",
    "Enlistment": "Dargaville",
    "Occupation": "Farm hand",
    "Address": "Dargaville",
    "Next of Kin": "Mrs Elizabeth Isaacs, Dargaville m",
    "Where Killed or Died": "Italy",
    "Cemetery Name": "Ancona War Italy",
    "Grave/Memorial Reference": "I L 13",
    "Last rank Held": "Pte",
    "Date of Birth": "1922",
    "Date of Death": "Fri Sep 22 1944 190000 GMT1200 New Zealand Standard Time",
    "Age": "22",
    "Burial/Cremation": "--",
    "AL": "Y",
    "Notes": "Son of William and Elizabeth Isaacs (nee Pirika), of Dargaville. Died of wounds. Note on Maori Battalion website. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Ivey",
    "Christian Name": "Maurice William",
    "Unit": "30 Fd Bty",
    "Regtl. Number": "24584",
    "Rank": "Gnr",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Auckland",
    "Occupation": "Tiler",
    "POW": "Y",
    "Place of capture": "Unknown",
    "Address": "64 Mains Ave, Whangarei",
    "Next of Kin": "Mrs I Ivey, 64 Mains Ave, Whangarei wife",
    "Date of Birth": "Sun Dec 05 1915 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Thu Sep 20 1990 190000 GMT1200 New Zealand Standard Time",
    "Age": "74",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Mon Sep 24 1990 19 00 00 GMT 1200 New Zealand Standard Time",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "Morris Morris Whg",
    "Husbands/Wives/Partners": "Irene Margaret Cullen",
    "Place of birth": "Waihi",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "POW. Son of William and Jean Eyred (Eyres) Ivey, nee Brown. Husband of Irene Margaret Ivey, nee Cullen, of Whangarei. Cremated at Maunu Cemetery & Crematorium, Whangarei; no other information. Place of birth: Waihi. Place of death: Whangarei. Myheritage.com. Ancestrylibrary.com.au. https://paperspast.natlib.govt.nz/newspapers/AS19420224.2.81.1?query whangarei"
  },
  {
    "Surname": "Ivey",
    "Christian Name": "Victor",
    "Unit": "N Z O C",
    "Regtl. Number": "533364",
    "Rank": "Pte",
    "Embarkation Dates": "J 43- D 43",
    "Marital Status": "M",
    "Enlistment": "Auckland",
    "Occupation": "Bootmaker",
    "Address": "127 Parnell Road, Parnell, Auck.",
    "Next of Kin": "Mrs A L Ivey, Motukaraka w",
    "Last rank Held": "Cpl",
    "Date of Birth": "Fri Jul 06 1917 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Wed May 06 1998 190000 GMT1200 New Zealand Standard Time",
    "Age": "80",
    "Burial/Cremation": "Cremation",
    "Cemetery/Urupa and Where Known Plot Number": "Manukau Memorial Gardens Papatoetoe Treem 28-018",
    "Funeral Director": "Grahams Funeral Home Tuakau",
    "Husbands/Wives/Partners": "Alice Louisa Beazley",
    "Place of birth": "Waihi or Thames",
    "Place of death": "Pukekohe Hospital Auckland",
    "AL": "Y",
    "Notes": "Son of Edward John and Margaret (Margaretta) Fredricka (Fredericka) Ivey, nee Johanson. Husband of Alice Louisa Ivey, nee Beazley, per the Marriage Index, of Motukaraka. Find a Grave website shows mother's name as Mary Ivey nee Williams. Place of death: Pukekohe Hospital, Auckland. Place of birth: Waihi or Thames. No other information. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Ivicevich",
    "Christian Name": "Cyril Anthony",
    "Unit": "21 Auck",
    "Name Variation": "Ivicevich, Tony",
    "Regtl. Number": "21578",
    "Rank": "Pte",
    "Embarkation Dates": "J 40",
    "Marital Status": "S",
    "Enlistment": "Waiuku",
    "Occupation": "Taxi Driver",
    "Address": "Waiuku",
    "Next of Kin": "Mr H C Ivicevich, 36 Norfolk St, Ponsonby, Auckland b",
    "Last rank Held": "Cpl",
    "Date of Birth": "Tue Feb 04 1913 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sun May 01 1994 190000 GMT1200 New Zealand Standard Time",
    "Age": "81",
    "Cemetery/Urupa and Where Known Plot Number": "Waikumete Cemetery Glen Eden Auckland Room Cath C 12-69",
    "Husbands/Wives/Partners": "Margaret Barbara Addie McArthur",
    "Place of birth": "Mangawhai",
    "Place of death": "Auckland Hospital Auckland",
    "AL": "Y",
    "Notes": "Greek Medal. Son of Anthony (Ante) (Anton) and Mary Ann Ivicevich, nee Kavalinovich (Kavali) . Husband of Margaret Barbara Addie Ivicevich, nee McArthur. Brother of Mr H C Ivicevich, of Ponsonby, Auckland. Place of birth: Mangawhai. Place of death: Auckland Hospital, Auckland. Bio on the Cenotaph record.Ancestrylibrary.com.au"
  },
  {
    "Surname": "Izard",
    "Christian Name": "Nowell Montgomerie",
    "Unit": "Inf Bde",
    "Regtl. Number": "470841",
    "Rank": "Mjr",
    "Embarkation Dates": "J 43- D 43",
    "Marital Status": "M",
    "Enlistment": "Wanganui",
    "Occupation": "Solicitor",
    "Address": "34 College Street, Wanganui",
    "Next of Kin": "Mrs C M Izard, P O Box 3, Gisborne w",
    "Last rank Held": "Mjr",
    "Date of Birth": "Sat Apr 27 1907 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Jun 01 1992 190000 GMT1200 New Zealand Standard Time",
    "Age": "85",
    "Cemetery/Urupa and Where Known Plot Number": "Wayby Cemetery Wellsford",
    "Husbands/Wives/Partners": "Cecil Maude Paddy Barker",
    "Place of birth": "Wanganui",
    "Place of death": "Wellsford",
    "AL": "Y",
    "Notes": "Son of William Arthur and Sybil Susannah Montgomerie Izard, nee Barker. Husband of Cecil Maude Paddy Izard, nee Barker, per the Marriage Index, of Gisborne. Place of death: Wellsford. Place of birth: Wanganui. Plot number unknown. Geni.com. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Izod",
    "Christian Name": "Lionel Charles",
    "Unit": "H Q 3 Div A S C",
    "Regtl. Number": "288775",
    "Rank": "A Cpl",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "S",
    "Enlistment": "Auckland",
    "Occupation": "Student",
    "Address": "Trinity College, Grafton, Auck.",
    "Next of Kin": "Mrs I O Izod, 6 Mains Ave, Whangarei m",
    "Date of Birth": "Sat May 07 1921 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Thu Sep 03 2015 190000 GMT1200 New Zealand Standard Time",
    "Age": "94",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Tue Sep 08 2015 19 00 00 GMT 1200 New Zealand Standard Time",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Funeral Director": "H Morris Ltd",
    "Husbands/Wives/Partners": "Peggy Eve Bartlett",
    "Place of birth": "NZ",
    "Place of death": "NZ",
    "AL": "Y",
    "Notes": "Son of Francis Lionel (Frank) and Ida Olive Izod, nee Wells, of Whangarei. Husband of Peggy Eve Izod, nee Bartlett. On the North cemetery Index; no other information available. Place of birth and death: New Zealand. Ancestrylibrary.com.au"
  }
];