const veteransDataZ = [
  {
    "Surname": "Zainey",
    "Christian Name": "Albert Anthony",
    "Unit": "3 Div Sigs",
    "Name Variation": "Zainey, Joseph Anthony Albert",
    "Regtl. Number": "478541",
    "Rank": "Gnr",
    "Embarkation Dates": "A 43-J 43",
    "Marital Status": "M",
    "Enlistment": "Auckland",
    "Occupation": "Freezing works employee",
    "Address": "62 Lingarth St, Remuera, Auckland",
    "Next of Kin": "Mrs E Zainey, 2 Kaiwau Rd, One Tree Hill, Auckland w",
    "Date of Birth": "Tue Feb 08 1916 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sun Jun 26 1983 190000 GMT1200 New Zealand Standard Time",
    "Age": "67",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Mangonui Cemetery Mangonui Public Lawn Division Block R Plot 1",
    "Funeral Director": "Unknown",
    "Husbands/Wives/Partners": "Elva McArthur",
    "Place of birth": "Auckland",
    "Place of death": "Kaitaia",
    "AL": "Y",
    "Notes": "Brother of Phillip George Zainey, who also served. Son of Joseph (Jos) Anthony and Florence (Flora) Elizabeth Zainey, nee Martin. Husband of Elva Zainey, nee McArthur, of One Tree Hill, Auckland. Albert Zainey is as per cemetery record. Place of birth: Auckland. Place of death: Kaitaia. The name Joseph Zainey is as per the Birth Index, parents being Joseph and Flora Zainey. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Zohrab",
    "Christian Name": "Amyas Constantine",
    "Unit": "Inf Bde",
    "Regtl. Number": "62541",
    "Rank": "Cpl",
    "Embarkation Dates": "J 41-S 41",
    "Marital Status": "M",
    "Enlistment": "Whangarei",
    "Occupation": "School teacher",
    "Address": "18 Mair Avenue, Whangarei",
    "Next of Kin": "Mrs M E Zohrab, 18 Mair Ave, Whangarei w",
    "Where Killed or Died": "Italy",
    "Cemetery Name": "Cassino War Italy",
    "Grave/Memorial Reference": "VI B 16",
    "Last rank Held": "Sgt",
    "Date of Birth": "Thu Aug 23 1906 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Fri Mar 17 1944 190000 GMT1200 New Zealand Daylight Time",
    "Age": "37",
    "Burial/Cremation": "--",
    "Husbands/Wives/Partners": "Margaret Ethel Bendall Mavis Lydia Ellen Benbow",
    "Place of birth": "Wellington",
    "AL": "Y",
    "Notes": "Brother Balfour Douglas Zohrab, also served. Son of Edward Goodwin Fortescue and Blanche Miriam Zohrab (nee Mabin), of Silverstream, Wellington. Husband of Margaret Ethel Zohrab, nee Bendall, per the Marriage Index, of Whangarei. Husband of Mavis Lydia Ellen Zohrab, nee Benbow. Died of wounds. Bio on Cenotaph database. Place of birth: Wellington. Ancestrylibrary.com.au"
  }
];