const veteransDataQ = [
  {
    "Surname": "Quaife",
    "Christian Name": "Lionel Walter Charles",
    "Unit": "36 Bn",
    "Regtl. Number": "68812",
    "Rank": "Pte",
    "Embarkation Dates": "J-M 42",
    "Marital Status": "S",
    "Enlistment": "Te Awamutu",
    "Occupation": "Farmer",
    "Address": "P.O. Te Awamutu",
    "Next of Kin": "Mr C Quaife, Paparoa f",
    "Last rank Held": "Pte",
    "Date of Birth": "Thu Mar 29 1917 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sun Jun 02 2002 190000 GMT1200 New Zealand Standard Time",
    "Age": "85",
    "Cemetery/Urupa and Where Known Plot Number": "St Mark s Church Anglican Cemetery Paparoa",
    "Husbands/Wives/Partners": "Rose Quaife",
    "Place of birth": "Paparoa",
    "Place of death": "Paparoa",
    "AL": "Y",
    "Notes": "Brother of Roy Mervyn Quaife, who also served. Son of Charles Goodwin (Goodwill) and Mabel Alice (Alice Mabel) Quaife, nee Sykes, of Paparoa. Husband of Rose Quaife. Place of birth and death: Paparoa. Father's middle name shown as Goodwill on the Cenotaph site. Plot no. is unknown. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quaife",
    "Christian Name": "Lionel Walter Charles",
    "Unit": "36 Bn",
    "Regtl. Number": "68812",
    "Rank": "Pte",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "S",
    "Enlistment": "Te Awamutu",
    "Occupation": "Farmer",
    "Address": "P.O. Te Awamutu",
    "Next of Kin": "Mr C Quaife, Paparoa f",
    "Last rank Held": "Pte",
    "Date of Birth": "Thu Mar 29 1917 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sun Jun 02 2002 190000 GMT1200 New Zealand Standard Time",
    "Age": "85",
    "Cemetery/Urupa and Where Known Plot Number": "St Mark s Church Anglican Cemetery Paparoa",
    "Husbands/Wives/Partners": "Rose Quaife",
    "Place of birth": "Paparoa",
    "Place of death": "Paparoa",
    "AL": "Y",
    "Notes": "Brother of Roy Mervyn Quaife, who also served. Son of Charles Goodwin (Goodwill) and Mabel Alice (Alice Mabel) Quaife, nee Sykes, of Paparoa. Husband of Rose Quaife. Place of birth and death: Paparoa. Father's middle name shown as Goodwill on the Cenotaph site. Plot no. is unknown. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quaife",
    "Christian Name": "Lionel Walter Charles",
    "Unit": "Inf Reinfs",
    "Regtl. Number": "68812",
    "Rank": "Pte",
    "Embarkation Dates": "J 45-D 45",
    "Marital Status": "S",
    "Enlistment": "Te Awamutu",
    "Occupation": "Farmer",
    "Address": "P.O. Te Awamutu",
    "Next of Kin": "Mr C G Quaife, Paparoa f",
    "Last rank Held": "Pte",
    "Date of Birth": "Thu Mar 29 1917 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sun Jun 02 2002 190000 GMT1200 New Zealand Standard Time",
    "Age": "85",
    "Cemetery/Urupa and Where Known Plot Number": "St Mark s Church Anglican Cemetery Paparoa",
    "Husbands/Wives/Partners": "Rose Quaife",
    "Place of birth": "Paparoa",
    "Place of death": "Paparoa",
    "AL": "Y",
    "Notes": "Brother of Roy Mervyn Quaife, who also served. Son of Charles Goodwin (Goodwill) and Mabel Alice (Alice Mabel) Quaife, nee Sykes, of Paparoa. Husband of Rose Quaife. Place of birth and death: Paparoa. Father's middle name shown as Goodwill on the Cenotaph site. Plot no. is unknown. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quaife",
    "Christian Name": "Roy Mervyn",
    "Unit": "2 Div A S C",
    "Regtl. Number": "292300",
    "Rank": "Dvr",
    "Embarkation Dates": "J 44-M 44",
    "Marital Status": "S",
    "Enlistment": "Auckland",
    "Occupation": "Farm hand",
    "Address": "16 Hauiti Rd, Otahuhu, Auck.",
    "Next of Kin": "Mr C G Quaife, Paparoa f",
    "Date of Birth": "Sat Jul 09 1921 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Apr 14 2008 190000 GMT1200 New Zealand Standard Time",
    "Age": "86",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Fri Apr 18 2008 19 00 00 GMT 1200 New Zealand Standard Time",
    "Cemetery/Urupa and Where Known Plot Number": "St Mark s Church Anglican Cemetery Paparoa",
    "Funeral Director": "Seddon Park Funeral Home",
    "Husbands/Wives/Partners": "Dorothy Aulgrane Peers",
    "Place of birth": "NZ",
    "Place of death": "Hamilton",
    "AL": "Y",
    "Notes": "Brother of Lionel Walter Charles Quaife, who also served. Son of Charles Goodwin (Goodwill) Mabel Alice (Alice Mabel) Quaife, nee Sykes, of Paparoa. Husband of Dorothy Aulgrane Quaife, nee Peers. Plot no. is unknown. Place of birth: New Zealand. Place of death: Hamilton. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quarterman",
    "Christian Name": "Allan",
    "Unit": "Inf Reinfs",
    "Regtl. Number": "70792",
    "Rank": "Pte",
    "Embarkation Dates": "J-M 42",
    "Marital Status": "S",
    "Enlistment": "Kaitaia",
    "Occupation": "Sheep farmer",
    "Address": "Takahue, R.D., Kaitaia",
    "Next of Kin": "Mr T H Quarterman, R.D., Kaitaia f",
    "Date of Birth": "Tue Jul 25 1916 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sun Oct 06 1996 200000 GMT1300 New Zealand Daylight Time",
    "Age": "80",
    "Place of birth": "NZ",
    "Place of death": "NZ",
    "AL": "Y",
    "Notes": "Son of Thomas Hardy and Vida May Quarterman, nee Swan, of Kaitaia. Place of birth and death: New Zealand. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quarterman",
    "Christian Name": "Allan",
    "Unit": "36 Bn",
    "Regtl. Number": "70792",
    "Rank": "Pte",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "S",
    "Enlistment": "Kaitaia",
    "Occupation": "Sheep farmer",
    "Address": "Takahue, R.D., Kaitaia",
    "Next of Kin": "Mr T H Quarterman, R.D., Kaitaia f",
    "Date of Birth": "Tue Jul 25 1916 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sun Oct 06 1996 200000 GMT1300 New Zealand Daylight Time",
    "Age": "80",
    "Place of birth": "NZ",
    "Place of death": "NZ",
    "AL": "Y",
    "Notes": "Son of Thomas Hardy and Vida May Quarterman, nee Swan, of Kaitaia. Place of birth and death: New Zealand. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quayle",
    "Christian Name": "Douglas",
    "Unit": "Inf Reinfs",
    "Regtl. Number": "29801",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "s",
    "Enlistment": "Nelson",
    "Occupation": "Forestry worker",
    "Address": "100 Ranfurly Rd, Epsom, Auckland",
    "Next of Kin": "Mr J T Quayle, Fraser St, Tauranga f",
    "Last rank Held": "L Cpl",
    "Date of Birth": "Sat Jul 18 1914 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Mon Dec 14 1987 210000 GMT1300 New Zealand Daylight Time",
    "Age": "73",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Thu Dec 17 1987 21 00 00 GMT 1300 New Zealand Daylight Time",
    "Cemetery/Urupa and Where Known Plot Number": "Maunu Cemetery Whangarei",
    "Funeral Director": "Morris Morris Whg",
    "Place of birth": "Auckland",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "Son of John Thomas and Ada Quayle, nee Blair, of Tauranga. Cremated at Maunu Cemetery, Whangarei. Plot no. is unknown. Place of birth and death: Auckland. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quayle",
    "Christian Name": "Percy",
    "Unit": "2 Div Sigs",
    "Name Variation": "Quayle, Percival",
    "Regtl. Number": "35110",
    "Rank": "Sgmn",
    "Embarkation Dates": "A 41- J 41",
    "Marital Status": "M",
    "Enlistment": "Whangarei",
    "Occupation": "Mechanician",
    "Address": "3 Princess St, Whangarei",
    "Next of Kin": "Mrs V I H Quayle, 3 Princess St, Whangarei w",
    "Last rank Held": "Sgmn",
    "Date of Birth": "Fri Dec 13 1912 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Tue Nov 30 1971 200000 GMT1200 New Zealand Standard Time",
    "Age": "58",
    "Cemetery/Urupa and Where Known Plot Number": "New Mount Wesley Cemetery Dargaville RSA Plot no 227",
    "Husbands/Wives/Partners": "Velma Isobel Isabel Hollywood Smeal",
    "Place of birth": "Ohakune",
    "Place of death": "Dargaville",
    "AL": "Y",
    "Notes": "Son of William Miller (Millar) and Sarah Louisa Quayle, nee Hobson. Husband of Velma Isobel (Isabel) Hollywood Quayle, nee Smeal, per the Marriage Index, of Whangarei. Another Percy Quayle is on the 1957 death index - age at death 65. This one is considered the more likely. Place of birth: Ohakune. Place of death: Dargaville. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Queen",
    "Christian Name": "George Campbell",
    "Unit": "H Q 21 Auck",
    "Regtl. Number": "22704",
    "Rank": "Pte",
    "Embarkation Dates": "J 40",
    "Marital Status": "M",
    "Enlistment": "Kaikohe",
    "Occupation": "Carpenter",
    "Address": "Kerikeri",
    "Next of Kin": "Mrs M C Queen, Care of G P Watkins, Station Rd, Penrose w",
    "Date of Birth": "Wed Sep 19 1900 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Tue May 17 1949 200000 GMT1200 New Zealand Standard Time",
    "Age": "48",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Kerikeri Wiroa Cemetery Kerikeri RSA Division Block VIII Plot 20",
    "Funeral Director": "Squire Funeral Services",
    "Husbands/Wives/Partners": "Mary Catherine Hellesoe",
    "Place of birth": "Paparoa",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "Son of James Carr and Charlotte Queen, nee Cartwright. Husband of Mary Catherine Queen, nee Hellesoe, of Penrose, Auckland. Place of birth: Paparoa. Place of death: Auckland. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quick",
    "Christian Name": "George",
    "Unit": "A A",
    "Regtl. Number": "248099",
    "Rank": "Gnr",
    "Embarkation Dates": "J 42- D 42",
    "Marital Status": "S",
    "Enlistment": "Hamilton",
    "Occupation": "Farm hand",
    "Address": "C - C Peach, Maramarua",
    "Next of Kin": "Mrs E Quick, C - Mrs W E Cotter, Portland m",
    "Date of Birth": "Sat Mar 27 1915 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Sun Aug 30 1987 190000 GMT1200 New Zealand Standard Time",
    "Age": "72",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Waikumete Cemetery Glen Eden Auckland WESTERN LAWN A Row 4 Plot 33",
    "Funeral Director": "W M Morrison Funeral Directors",
    "Husbands/Wives/Partners": "Annie Mavis Hunt",
    "Place of birth": "Gisborne",
    "Place of death": "Auckland",
    "AL": "Y",
    "Notes": "Son of William Henry and Elizabeth Quick, nee Flint, of Portland. Husband of Annie Mavis Quick, nee Hunt. Place of birth: Gisborne. Place of death: Auckland. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quigg",
    "Christian Name": "Roy",
    "Unit": "24 Auck",
    "Regtl. Number": "24248",
    "Rank": "Pte",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "N Z Railways",
    "Address": "21 First Ave, Whangarei",
    "Next of Kin": "Mrs M Quigg, 4 Enfield St, Mt. Eden, Auckland mother",
    "Date of Birth": "Fri Sep 20 1918 183000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Tue Jan 20 1970 200000 GMT1200 New Zealand Standard Time",
    "Age": "51",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Hamilton Park Cemetery Hamilton RSA-06-083",
    "Funeral Director": "James R Hill Funeral Directors",
    "Husbands/Wives/Partners": "Melva Nora Beach",
    "Place of birth": "Waihi",
    "Place of death": "Hamilton",
    "AL": "Y",
    "Notes": "POW. Son of Francis Joseph and Mary Quigg, nee Dunstan, of Mt. Eden, Auckland. Husband of Melva Nora Quigg, nee Beach. Place of birth: Waihi. Place of death: Hamilton. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quilty",
    "Christian Name": "Patrick Thomas",
    "Unit": "21 Auck",
    "Regtl. Number": "22054",
    "Rank": "Pte",
    "Embarkation Dates": "J 40",
    "Marital Status": "S",
    "Enlistment": "Dargaville",
    "Occupation": "Labourer",
    "POW": "Y",
    "Place of capture": "Unknown",
    "Address": "Donnelly's Crossing",
    "Next of Kin": "Mrs H Quilty, Donnelly's Crossing m",
    "Last rank Held": "Pte",
    "Date of Birth": "Thu May 10 1917 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Thu Aug 18 2005 190000 GMT1200 New Zealand Standard Time",
    "Age": "88",
    "Cemetery/Urupa and Where Known Plot Number": "Pyes Pa Cemetery Tauranga",
    "Husbands/Wives/Partners": "Alma Martelletti",
    "Place of birth": "Thames",
    "Place of death": "Tauranga",
    "AL": "Y",
    "Notes": "POW. Son of Thomas and Hannah Quilty, nee Leonard, of Donnelly s Crossing. Husband of Alma Quilty, nee Martelletti. Place of birth: Thames. Place of death: Tauranga. Familysearch.org. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quin",
    "Christian Name": "Charles Stuart",
    "Unit": "N Z M C",
    "Name Variation": "Quinn, Charles Stuart",
    "Regtl. Number": "589906",
    "Rank": "Pte",
    "Embarkation Dates": "J 44-M 44",
    "Marital Status": "M",
    "Enlistment": "Te Awamutu",
    "Occupation": "Dairy officer",
    "POW": "Y",
    "Place of capture": "Crete",
    "Address": "13 Buchanan St, Auckland",
    "Next of Kin": "Mrs A J Quin, 40 Waihi Rd, Hawera, w",
    "Last rank Held": "Cpl",
    "Date of Birth": "Tue Apr 05 1904 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sat Jul 05 1975 190000 GMT1200 New Zealand Standard Time",
    "Age": "71",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Maunu Cemetery Whangarei RSA Block Seventeen Plot 749",
    "Funeral Director": "Morris Morris Funeral Home",
    "Husbands/Wives/Partners": "Audrey Jessie Willis",
    "Place of birth": "Hawera",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "Son of Joseph and Helen Eve Mary (Eve Ellen Mary) Quin, nee McDonald. Husband of Audrey Jessie Quin, nee Willis. Name misspelt as Quinn on the cemetery record. Place of birth: Hawera. Place of death: Whangarei. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quin",
    "Christian Name": "James Bernard",
    "Unit": "20 Fd Coy",
    "Regtl. Number": "28531",
    "Rank": "Spr",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Wellington",
    "Occupation": "Fireman",
    "Address": "Central Fire Station, Wellington",
    "Next of Kin": "Mrs M Quin, Tauraroa m",
    "Last rank Held": "Sgt",
    "Date of Birth": "Wed Jan 26 1916 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Mon Dec 31 1990 210000 GMT1300 New Zealand Daylight Time",
    "Age": "74",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Taita Cemetery Naenae Lower Hutt RSA Soldiers Burial Block 10 Row U Plot 01",
    "Funeral Director": "Croft Funeral Home Limited",
    "Husbands/Wives/Partners": "Kathleen Margaret Weir Glubb",
    "Place of birth": "Mangapai",
    "Place of death": "Lower Hutt",
    "AL": "Y",
    "Notes": "Brother of John Joseph Quin, who also served. Son of Thomas Alexander and Mary Quin, nee Sands, of Tauraroa. Husband of Kathleen Margaret Quin, nee Weir (Glubb). Place of birth: Mangapai. Place of death: Lower Hutt. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quin",
    "Christian Name": "James Bernard",
    "Unit": "2 Div N Z E",
    "Regtl. Number": "28531",
    "Rank": "Spr",
    "Embarkation Dates": "J 41-S 41",
    "Marital Status": "S",
    "Enlistment": "Wellington",
    "Occupation": "Fireman",
    "Address": "Central Fire Station, Wellington",
    "Next of Kin": "Mrs M Quin, Tauraroa m",
    "Last rank Held": "Sgt",
    "Date of Birth": "Wed Jan 26 1916 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Mon Dec 31 1990 210000 GMT1300 New Zealand Daylight Time",
    "Age": "74",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Taita Cemetery Naenae Lower Hutt RSA Soldiers Burial Block 10 Row U Plot 01",
    "Funeral Director": "Croft Funeral Home Limited",
    "Husbands/Wives/Partners": "Kathleen Margaret Weir Glubb",
    "Place of birth": "Mangapai",
    "Place of death": "Lower Hutt",
    "AL": "Y",
    "Notes": "Brother of John Joseph Quin, who also served. Son of Thomas Alexander and Mary Quin, nee Sands, of Tauraroa. Husband of Kathleen Margaret Quin, nee Weir (Glubb). Place of birth: Mangapai. Place of death: Lower Hutt. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quin",
    "Christian Name": "John Joseph",
    "Unit": "18 A Tps Coy",
    "Name Variation": "Quin, Huck",
    "Regtl. Number": "32221",
    "Rank": "Spr",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Transport-driver",
    "Address": "Maungakaramea",
    "Next of Kin": "Mrs Mary Quin, Maungakaramea, Whangarei mother",
    "Last rank Held": "L Cpl",
    "Date of Birth": "Sun Nov 29 1908 193000 GMT1130 New Zealand Daylight Time",
    "Date of Death": "Wed Jun 22 1960 190000 GMT1200 New Zealand Standard Time",
    "Age": "51",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "RSA Block Ten Plot 321 Maunu",
    "Funeral Director": "Newberrys Whg",
    "Husbands/Wives/Partners": "Phylis Amelia Gunson",
    "Place of birth": "Burnett s Face Denniston",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "Brother of James Bernard Quin, who also served. Son of Thomas Alexander and Mary Quin, nee Sands, of Tauraroa. Husband of Phylis Amelia Quin, nee Gunson. Place of birth: Burnett's Face, Denniston. Place of death: Whangarei. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quincey",
    "Christian Name": "Frank",
    "Unit": "2 Div Pet Coy",
    "Regtl. Number": "12118",
    "Rank": "Dvr",
    "Embarkation Dates": "J 40-M 41",
    "Marital Status": "S",
    "Enlistment": "Burnham",
    "Occupation": "Fitter",
    "Address": "108 Bank St, Whangarei",
    "Next of Kin": "Mr E Quincey, 134 Ravenhill Ave, Belfast, Ireland father",
    "Date of Birth": "1902",
    "Date of Death": "Mon Dec 06 1965 200000 GMT1200 New Zealand Daylight Time",
    "Age": "63",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Forest Lawn Block Nineteen Plot 1351 Maunu",
    "Funeral Director": "Morris Morris Whg",
    "Husbands/Wives/Partners": "Margaret Wilhelmina Franks or Biggs",
    "Place of birth": "Belfast Antrim N Ireland",
    "Place of death": "Whangarei",
    "AL": "Y",
    "Notes": "POW. Son of Elijah and Guthrie Quincey, nee Liveston, of Belfast, Ireland. Husband of Margaret Wilhelmina Quincey, nee Franks or nee Biggs? Born in December 1902. Place of birth: Belfast, Antrim, N. Ireland. Place of death: Whangarei. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quinlan",
    "Christian Name": "William Roy Gavin",
    "Unit": "2 Div Arty",
    "Regtl. Number": "282450",
    "Rank": "Gnr",
    "Embarkation Dates": "J 44-M 44",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Painter",
    "POW": "Y",
    "Place of capture": "Greece",
    "Address": "3 Roycroft St, Waihi",
    "Next of Kin": "Mrs E Quinlan, 3 Roycroft St, Waihi m",
    "Last rank Held": "Bdr",
    "Date of Birth": "Sat Jun 19 1909 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Thu Feb 15 1979 210000 GMT1300 New Zealand Daylight Time",
    "Age": "69",
    "Burial/Cremation": "Burial",
    "Cemetery/Urupa and Where Known Plot Number": "Waihi Public Cemetery Waihi Section SER Block RSA Lot 279",
    "Husbands/Wives/Partners": "Nora Lopdell",
    "Place of birth": "Waihi",
    "Place of death": "Waihi",
    "AL": "Y",
    "Notes": "Son of Herbert Edward and Ellen Quinlan, nee Gavin, of Waihi. Husband of Nora Quinlan, nee Lopdell. Place of birth and death: Waihi. Ancestrylibrary.com.au"
  },
  {
    "Surname": "Quintal",
    "Christian Name": "Norfolk Adrian Samuel",
    "Unit": "4 Res M T Coy",
    "Name Variation": "Quintal, Samuel Adrian Norfolk",
    "Regtl. Number": "3711",
    "Rank": "Pte",
    "Embarkation Dates": "M 40",
    "Marital Status": "S",
    "Enlistment": "Whangarei",
    "Occupation": "Labourer Public Works",
    "Address": "Parua Bay",
    "Next of Kin": "Mrs S Quintal, C - F R Carter, Northcote, Auckland mother",
    "Date of Birth": "Thu Aug 27 1914 193000 GMT1130 New Zealand Standard Time",
    "Date of Death": "Sun Sep 29 1974 190000 GMT1200 New Zealand Standard Time",
    "Age": "60",
    "Burial/Cremation": "Cremation",
    "Ashes/Burial": "Tue Oct 01 1974 19 00 00 GMT 1200 New Zealand Standard Time",
    "Cemetery/Urupa and Where Known Plot Number": "See note",
    "Husbands/Wives/Partners": "Phyllis Mary Andrews",
    "Place of birth": "Auckland",
    "Place of death": "Tauranga",
    "AL": "Y",
    "Notes": "POW. Son of Frank Joseph and Sarah Quintal, nee Carliss, of Northcote, Auckland. Husband of Phyllis Mary Quintal, nee Andrews. Place of birth: Auckland. Place of death: Tauranga. Cremated at Pyes Pa Cemetery and Crematorium, Tauranga. No other information. Ancestrylibrary.com.au. Birth and death recorded as Samuel Adrian Norfolk Quintal. https://gw.geneanet.org/monartque?lang en&pz pierre&nz tremblay&ocz 19&p norfolk adrian samuel&n quintal"
  }
];